import {
  Droplets,
  Sun,
  Wrench,
  Shield,
  Clock,
  Award,
  Zap,
  ThumbsUp,
  CheckCircle,
  Waves,
  Refrigerator,
  WashingMachine,
} from "lucide-react";
import { ADDRESS_LINES, CALL, MAPS_DIRECTIONS_URL, PHONE_DISPLAY, WHATSAPP } from "./constants";
import type {
  AmcPlanItem,
  BookingStep,
  ContactChannelCard,
  FooterServiceLink,
  HeroFeatureCard,
  ProductItem,
  ServiceItem,
  StatItem,
  TestimonialItem,
  TrustItem,
  WhyChoosePoint,
} from "./types";

export const STATS: StatItem[] = [
  { val: "12+", label: "Years Experience" },
  { val: "8,500+", label: "Happy Customers" },
  { val: "15,000+", label: "Services Done" },
  { val: "98%", label: "Satisfaction Rate" },
];

export const HERO_FEATURE_CARDS: HeroFeatureCard[] = [
  { icon: Droplets, title: "RO Purifiers", sub: "From ₹8,999", color: "from-cyan-500 to-blue-600" },
  { icon: Sun, title: "Solar Systems", sub: "Save 80% Bills", color: "from-amber-500 to-orange-500" },
  { icon: Shield, title: "AMC Plans", sub: "From ₹999/yr", color: "from-teal-500 to-cyan-600" },
  { icon: Wrench, title: "Same-Day Service", sub: "All Brands", color: "from-blue-600 to-indigo-600" },
];

export const TRUST_ITEMS: TrustItem[] = [
  { icon: Award, text: "ISO Certified" },
  { icon: ThumbsUp, text: "MNRE Empanelled" },
  { icon: Shield, text: "Genuine Spare Parts" },
  { icon: Clock, text: "Same-Day Service" },
  { icon: CheckCircle, text: "2-Year Warranty" },
];

export const SERVICES: ServiceItem[] = [
  {
    slug: "ro-water-purifier",
    icon: Droplets,
    title: "RO Water Purifiers",
    tamil: "RO நீர் சுத்திகரிப்பு",
    desc: "Premium multi-stage filtration systems for pure, safe drinking water for your family.",
    color: "from-cyan-500 to-blue-600",
  },
  {
    slug: "ro-service",
    icon: Wrench,
    title: "RO Service & Repair",
    tamil: "சேவை & பழுது",
    desc: "Expert technicians for same-day service, filter replacement, and complete overhaul.",
    color: "from-blue-500 to-indigo-600",
  },
  {
    slug: "amc",
    icon: Shield,
    title: "AMC Plans",
    tamil: "வருடாந்திர பராமரிப்பு",
    desc: "Comprehensive annual maintenance contracts with priority support and free filters.",
    color: "from-teal-500 to-cyan-600",
  },
  {
    slug: "solar-water-heater",
    icon: Sun,
    title: "Solar Water Heater",
    tamil: "சோலார் வாட்டர் ஹீட்டர்",
    desc: "High-efficiency solar thermal systems. Cut electricity bills by up to 80%.",
    color: "from-amber-500 to-orange-500",
  },
  {
    slug: "solar-panel",
    icon: Zap,
    title: "Solar Panel Installation",
    tamil: "சோலார் பேனல்",
    desc: "Grid-tie and off-grid photovoltaic systems with MNRE-certified installations.",
    color: "from-yellow-500 to-amber-600",
  },
  {
    slug: "water-softener",
    icon: Waves,
    title: "Water Softener",
    tamil: "வாட்டர் சாஃப்டனர்",
    desc: "Ion-exchange softening systems that protect appliances and skin from hard water.",
    color: "from-sky-500 to-blue-500",
  },
  {
    slug: "fridge-repair",
    icon: Refrigerator,
    title: "Fridge Repair",
    tamil: "குளிர்சாதனப் பெட்டி பழுது",
    desc: "All brands. Gas refilling, compressor, thermostat, and door seal repairs.",
    color: "from-blue-600 to-violet-600",
  },
  {
    slug: "washing-machine-repair",
    icon: WashingMachine,
    title: "Washing Machine Repair",
    tamil: "வாஷிங் மெஷின் பழுது",
    desc: "Top-load & front-load specialists. Motor, drum, PCB and pump repairs.",
    color: "from-indigo-500 to-blue-600",
  },
];

export const PRODUCTS: ProductItem[] = [
  {
    name: "Aqua Shark",
    brand: "WATERNET",
    tag: "Best Seller",
    price: "₹8,500",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "8L Tank",
    img: "/products/aqua_shark.jpeg",
    features: ["Alkaline RO purifier", "Auto on/off function", "Antibacterial tank", "Wall/table top mount"],
  },
  {
    name: "Blue Rock",
    brand: "WATERNET",
    tag: "TDS Control",
    price: "₹9,500",
    mrp: null,
    liters: "18L/Hr",
    stages: "6 Stage",
    tank: "8L Tank",
    img: "/products/blue_rock.jpeg",
    features: ["Fully automatic service", "TDS controller", "Water scale indicator", "Computer controlled operation"],
  },
  {
    name: "Aqua Angel",
    brand: "WATERNET",
    tag: "Alkaline",
    price: "₹12,500",
    mrp: null,
    liters: "18L/Hr",
    stages: "7 Stage",
    tank: "10L Tank",
    img: "/products/AQUA_ANGEL.jpeg",
    features: ["Detachable washable tank", "LED indicator panel", "Anti-bacterial coating", "Voltage spike protection"],
  },
  {
    name: "Aqua Zebra",
    brand: "WATERNET",
    tag: "Alkaline RO",
    price: "₹15,500",
    mrp: null,
    liters: "12L/Hr",
    stages: "9 Stage",
    tank: "10L Tank",
    img: "/products/AQUA_ZEBRA.jpeg",
    features: ["Anti-oxidant alkaline water", "LED indicator", "Detachable washable tank", "TDS mineral technology"],
  },
  {
    name: "Crown Star",
    brand: "BLUE MOUNT",
    tag: "Most Advanced",
    price: "₹17,500",
    mrp: null,
    liters: "18L/Hr",
    stages: "12 Stage",
    tank: "12L Tank",
    img: "/products/CROWN_STAR.jpeg",
    features: ["12-stage purification", "Anti-oxidant alkaline tech", "Fully automatic service", "Computer controlled operation"],
  },
  {
    name: "Waternet Tulips",
    brand: "WATERNET",
    tag: "Steel Body",
    price: "₹22,500",
    mrp: null,
    liters: "18L/Hr",
    stages: "12 Stage",
    tank: "9L Tank",
    img: "/products/WATERNET_TULIPS.jpeg",
    features: ["304 grade stainless steel", "Anti-oxidant alkaline water", "Detachable washable tank", "Fully automatic service"],
  },
  {
    name: "Whale RO + UF",
    brand: "WHALE",
    tag: "Family Size",
    price: "Call for Price",
    mrp: null,
    liters: "25L Tank",
    stages: "RO + UF",
    tank: "25L Tank",
    img: "/products/waternet_whale_25L.jpeg",
    features: ["Extra large 25L storage", "Dual RO + UF purification", "Ideal for large families", "Modern designer look"],
  },
  {
    name: "AQUA  RAGA 2090 RUBY PINK",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/1-1.jpg",
    features: ["Water Purifier With Out Storage", "Per Hour Flow 12 Ltrs", "Per Day Consumption: 30-60 Ltrs"],
  },
  {
    name: "AQUA 2090 BLUE",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/1-2.jpg",
    features: ["Water Purifier With Out Storage", "Per Hour Flow 12 Ltrs", "Per Day Consumption: 30-60 Ltrs"],
  },
  {
    name: "AQUA 2090 DEEP PURPLE",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/1-3.jpg",
    features: ["Water Purifier With Out Storage", "Per Hour Flow 12 Ltrs", "Per Day Consumption: 30-60 Ltrs"],
  },
  {
    name: "AQUA 2090 GREEN",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/1-4.jpg",
    features: ["Water Purifier With Out Storage", "Per Hour Flow 12 Ltrs", "Per Day Consumption: 30-60 Ltrs"],
  },
  {
    name: "AQUA 2090 MIRROR BLACK",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/1-5.jpg",
    features: ["Water Purifier With Out Storage", "Per Hour Flow 12 Ltrs", "Per Day Consumption: 30-60 Ltrs"],
  },
  {
    name: "AQUA RAGA 2090 DAYTONA SILVER",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/1-6.jpg",
    features: ["Water Purifier With Out Storage", "Per Hour Flow 12 Ltrs", "Per Day Consumption: 30-60 Ltrs"],
  },
  {
    name: "AQUA RAGA 2090 HERITAGE GOLD",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/1-7.jpg",
    features: ["Water Purifier With Out Storage", "Per Hour Flow 12 Ltrs", "Per Day Consumption: 30-60 Ltrs"],
  },
  {
    name: "AQUA RAGA 2090 ROLEX GREEN",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/1-8.jpg",
    features: ["Water Purifier With Out Storage", "Per Hour Flow 12 Ltrs", "Per Day Consumption: 30-60 Ltrs"],
  },
  {
    name: "AQUA RAGA 2090 SIERRA BLUE",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/1-9.jpg",
    features: ["Water Purifier With Out Storage", "Per Hour Flow 12 Ltrs", "Per Day Consumption: 30-60 Ltrs"],
  },
  {
    name: "AQUA ROMA CHERRY SILVER",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/1-10.jpg",
    features: ["Water Purifier With Out Storage", "Per Hour Flow 12 Ltrs", "Per Day Consumption: 30-60 Ltrs"],
  },
  {
    name: "AQUA ROMA METALIC BLUE",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/1-11.jpg",
    features: ["Water Purifier With Out Storage", "Per Hour Flow 12 Ltrs", "Per Day Consumption: 30-60 Ltrs"],
  },
  {
    name: "AQUA ROMA METALLIC GREEN",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/1-12.jpg",
    features: ["Water Purifier With Out Storage", "Per Hour Flow 12 Ltrs", "Per Day Consumption: 30-60 Ltrs"],
  },
  {
    name: "AQUA ROMA WHTE",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/1-13.jpg",
    features: ["Water Purifier With Out Storage", "Per Hour Flow 12 Ltrs", "Per Day Consumption: 30-60 Ltrs"],
  },
  {
    name: "AQUA V5 BLACK",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/1-14.jpg",
    features: ["Water Purifier With Out Storage", "Per Hour Flow 12 Ltrs", "Per Day Consumption: 30-60 Ltrs"],
  },
  {
    name: "AQUA V5 BLUE",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/1-15.jpg",
    features: ["Water Purifier With Out Storage", "Per Hour Flow 12 Ltrs", "Per Day Consumption: 30-60 Ltrs"],
  },
  {
    name: "AQUA V5 GREY",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/1-16.jpg",
    features: ["Water Purifier With Out Storage", "Per Hour Flow 12 Ltrs", "Per Day Consumption: 30-60 Ltrs"],
  },
  {
    name: "AQUA V5 MAROON",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/1-17.jpg",
    features: ["Water Purifier With Out Storage", "Per Hour Flow 12 Ltrs", "Per Day Consumption: 30-60 Ltrs"],
  },
  {
    name: "EMIRA BLACK",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/1-18.jpg",
    features: ["Water Purifier With Out Storage", "Per Hour Flow 12 Ltrs", "Per Day Consumption: 30-60 Ltrs"],
  },
  {
    name: "EMIRA CHERRY RED",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/1-19.jpg",
    features: ["Water Purifier With Out Storage", "Per Hour Flow 12 Ltrs", "Per Day Consumption: 30-60 Ltrs"],
  },
  {
    name: "EMIRA WHITE",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/1-20.jpg",
    features: ["Water Purifier With Out Storage", "Per Hour Flow 12 Ltrs", "Per Day Consumption: 30-60 Ltrs"],
  },
  {
    name: "HI FLO CHERRY RED",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/1-21.jpg",
    features: ["Water Purifier With Out Storage", "Per Hour Flow 12 Ltrs", "Per Day Consumption: 30-60 Ltrs"],
  },
  {
    name: "HI FLO METALLIC GREY",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/1-22.jpg",
    features: ["Water Purifier With Out Storage", "Per Hour Flow 12 Ltrs", "Per Day Consumption: 30-60 Ltrs"],
  },
  {
    name: "HI FLO METTALIC BLACK",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/1-23.jpg",
    features: ["Water Purifier With Out Storage", "Per Hour Flow 12 Ltrs", "Per Day Consumption: 30-60 Ltrs"],
  },
  {
    name: "HI FLO SKY BLUE",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/1-24.jpg",
    features: ["Water Purifier With Out Storage", "Per Hour Flow 12 Ltrs", "Per Day Consumption: 30-60 Ltrs"],
  },
  {
    name: "HI FLO STD BLUE",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/1-25.jpg",
    features: ["Water Purifier With Out Storage", "Per Hour Flow 12 Ltrs", "Per Day Consumption: 30-60 Ltrs"],
  },
  {
    name: "LEXZON AQUA BLUE",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/1-26.jpg",
    features: ["Water Purifier With Out Storage", "Per Hour Flow 12 Ltrs", "Per Day Consumption: 30-60 Ltrs"],
  },
  {
    name: "LEXZON AQUA GREEN",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/1-27.jpg",
    features: ["Water Purifier With Out Storage", "Per Hour Flow 12 Ltrs", "Per Day Consumption: 30-60 Ltrs"],
  },
  {
    name: "LEXZON GREY",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/1-28.jpg",
    features: ["Water Purifier With Out Storage", "Per Hour Flow 12 Ltrs", "Per Day Consumption: 30-60 Ltrs"],
  },
  {
    name: "LEXZON METTALIC BLUE",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/1-29.jpg",
    features: ["Water Purifier With Out Storage", "Per Hour Flow 12 Ltrs", "Per Day Consumption: 30-60 Ltrs"],
  },
  {
    name: "LX ONE AURORA RED",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/1-30.jpg",
    features: ["Water Purifier With Out Storage", "Per Hour Flow 12 Ltrs", "Per Day Consumption: 30-60 Ltrs"],
  },
  {
    name: "LX ONE CHARCOAL BLACK",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/1-31.jpg",
    features: ["Water Purifier With Out Storage", "Per Hour Flow 12 Ltrs", "Per Day Consumption: 30-60 Ltrs"],
  },
  {
    name: "LX ONE GUN METAL",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/1-32.jpg",
    features: ["Water Purifier With Out Storage", "Per Hour Flow 12 Ltrs", "Per Day Consumption: 30-60 Ltrs"],
  },
  {
    name: "LX ONE POLAR WHITE",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/1-33.jpg",
    features: ["Water Purifier With Out Storage", "Per Hour Flow 12 Ltrs", "Per Day Consumption: 30-60 Ltrs"],
  },
  {
    name: "LX ONE WHITE GOLD",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/1-34.jpg",
    features: ["Water Purifier With Out Storage", "Per Hour Flow 12 Ltrs", "Per Day Consumption: 30-60 Ltrs"],
  },
  {
    name: "PUROSIS COPPER GOLD",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/1-35.jpg",
    features: ["Water Purifier With Out Storage", "Per Hour Flow 12 Ltrs", "Per Day Consumption: 30-60 Ltrs"],
  },
  {
    name: "Wallmount",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹5000",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/1-wallmount.jpg",
    features: ["Water Purifier With Out Storage", "Per Hour Flow 12 Ltrs", "Per Day Consumption: 30-60 Ltrs"],
  },
  {
    name: "Dolphin",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹7000",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "10L Tank",
    img: "/products/2dolphin.jpg",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
  },
  {
    name: "Dolphin Red",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹7500",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "10L Tank",
    img: "/products/2c-dolphin-red.jpg",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
  },
  {
    name: "Dolphin Black",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹7500",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "10L Tank",
    img: "/products/2a-dolphin-black.jpg",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
  },
  {
    name: "Dolphin Grey",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹7500",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "10L Tank",
    img: "/products/2b-dolphin-gray.jpg",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
  },
  {
    name: "H2O Black",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹7500",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "10L Tank",
    img: "/products/3-h2o-black.jpg",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
  },
  {
    name: "H2O Red",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹7500",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "10L Tank",
    img: "/products/4-h2o-red.jpg",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
  },
  {
    name: "Aqua Touch Black",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹8500",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "10L Tank",
    img: "/products/aqua-touch-black.jpeg",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
  },
  {
    name: "Aqua Touch Red",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹8500",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "10L Tank",
    img: "/products/6-aqua-touch-red.jpg",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
  },
  {
    name: "Aqua Touch Grey",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹8500",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "10L Tank",
    img: "/products/aqua-touch-greychange.jpeg",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
  },
  {
    name: "Aqua Touch Blue",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹8500",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "10L Tank",
    img: "/products/8-aqua-touch-blue.jpg",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
  },
  {
    name: "AQUA TOUCH COMRADE BLUE",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹8500",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "10L Tank",
    img: "/products/aqua-touch-comrade-bluechange.jpeg",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
  },
  {
    name: "Aqua Touch Skyblue",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹8500",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "10L Tank",
    img: "/products/10-aqua-touch-sky-blue.jpg",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
  },
  {
    name: "Water Lilly Blue",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹8500",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "10L Tank",
    img: "/products/11-water-lilly-blue.jpg",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
  },
  {
    name: "Water Lilly Comrade Blue",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹8500",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "10L Tank",
    img: "/products/water-lilly-comrade-bluechange.jpeg",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
  },
  {
    name: "Water Lilly Sky Blue",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹8500",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "10L Tank",
    img: "/products/12-water-lilly-skyblue.jpg",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
  },
  {
    name: "Water Lilly Black",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹8500",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "10L Tank",
    img: "/products/water-lilly-blackchange.jpeg",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
  },
  {
    name: "Water Lilly Grey",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹8500",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "10L Tank",
    img: "/products/15-water-lilly-grey.jpg",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
  },
  {
    name: "Water Lilly Red",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹8500",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "10L Tank",
    img: "/products/water-lilly-redchange.jpeg",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
  },
  {
    name: "Apple Black",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹8000",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "10L Tank",
    img: "/products/28-apple-black.jpg",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
  },
  {
    name: "Apple Blue",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹8000",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "10L Tank",
    img: "/products/29-apple-blue.jpg",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
  },
  {
    name: "Aqua Lio Blue",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹8500",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "10L Tank",
    img: "/products/31-aqua-lio-blue.jpg",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
  },
  {
    name: "Aqua Lio Black",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹8500",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "10L Tank",
    img: "/products/aqua-lio-bluechange.jpeg",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
  },
  {
    name: "Aqua Lio Sky Blue",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹8500",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "10L Tank",
    img: "/products/32-aqua-lio-skyblue.jpg",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
  },
  {
    name: "Aqua Mars Blue",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹8000",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "10L Tank",
    img: "/products/33-aqua-mars-blue.jpg",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
  },
  {
    name: "Aqua Mars Sky Blue",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹8000",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "10L Tank",
    img: "/products/34-aqua-mars-green.jpg",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
  },
  {
    name: "Aqua Mars Grey",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹8000",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "10L Tank",
    img: "/products/35-aqua-mars-grey.jpg",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
  },
  {
    name: "Aqua Mars Black",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹8000",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "10L Tank",
    img: "/products/36-aqua-mars-black.jpg",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
  },
  {
    name: "Aqua Mars Stone Badge",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹8000",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "10L Tank",
    img: "/products/37-aqua-mars-stone-badge.jpg",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
  },
  {
    name: "Aqua Glance",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹8000",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "10L Tank",
    img: "/products/38-aqua-glance.jpg",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
  },
  {
    name: "A Star Blue",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹8000",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "10L Tank",
    img: "/products/39a-star-blue.jpg",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
  },
  {
    name: "Water Pia Blue",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹8500",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "10L Tank",
    img: "/products/41-water-pia-blue.jpg",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
  },
  {
    name: "AQUA FLIP BLUE",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO+UV",
    tank: "Standard Tank",
    img: "/products/2-1.jpg",
    features: ["RO + UV WATER PURIFIER WITH STORAGE"],
  },
  {
    name: "AQUA FLIP GREEN",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO+UV",
    tank: "Standard Tank",
    img: "/products/2-2.jpg",
    features: ["RO + UV WATER PURIFIER WITH STORAGE"],
  },
  {
    name: "AQUA FLIP",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO+UV",
    tank: "Standard Tank",
    img: "/products/2-3.jpg",
    features: ["RO + UV WATER PURIFIER WITH STORAGE"],
  },
  {
    name: "AQUA INNOVICA AQUA GREEN",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO+UV",
    tank: "Standard Tank",
    img: "/products/2-4.jpg",
    features: ["RO + UV WATER PURIFIER WITH STORAGE"],
  },
  {
    name: "AQUA INNOVICA CANDY WHITE BLUE",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO+UV",
    tank: "Standard Tank",
    img: "/products/2-5.jpg",
    features: ["RO + UV WATER PURIFIER WITH STORAGE"],
  },
  {
    name: "AQUA INNOVICA METTALIC ENERGY BLUE",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO+UV",
    tank: "Standard Tank",
    img: "/products/2-6.jpg",
    features: ["RO + UV WATER PURIFIER WITH STORAGE"],
  },
  {
    name: "AQUA INNOVICA METTALIC STEEL GREY",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO+UV",
    tank: "Standard Tank",
    img: "/products/2-7.jpg",
    features: ["RO + UV WATER PURIFIER WITH STORAGE"],
  },
  {
    name: "AQUA INNOVICA MIRROR BLACK",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO+UV",
    tank: "Standard Tank",
    img: "/products/2-8.jpg",
    features: ["RO + UV WATER PURIFIER WITH STORAGE"],
  },
  {
    name: "LX TWO ADMIRAL BLUE",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO+UV",
    tank: "Standard Tank",
    img: "/products/2-9.jpg",
    features: ["RO + UV WATER PURIFIER WITH STORAGE"],
  },
  {
    name: "LX TWO ANTIQUE BRONZE",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO+UV",
    tank: "Standard Tank",
    img: "/products/2-10.jpg",
    features: ["RO + UV WATER PURIFIER WITH STORAGE"],
  },
  {
    name: "LX TWO CHARCOAL BLACK",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO+UV",
    tank: "Standard Tank",
    img: "/products/2-11.jpg",
    features: ["RO + UV WATER PURIFIER WITH STORAGE"],
  },
  {
    name: "LX TWO CHERRY RED",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO+UV",
    tank: "Standard Tank",
    img: "/products/2-12.jpg",
    features: ["RO + UV WATER PURIFIER WITH STORAGE"],
  },
  {
    name: "LX TWO EMERALD GREEN",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO+UV",
    tank: "Standard Tank",
    img: "/products/2-13.jpg",
    features: ["RO + UV WATER PURIFIER WITH STORAGE"],
  },
  {
    name: "LX TWO GUN METAL",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO+UV",
    tank: "Standard Tank",
    img: "/products/2-14.jpg",
    features: ["RO + UV WATER PURIFIER WITH STORAGE"],
  },
  {
    name: "LX TWO OCEAN BLUE",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO+UV",
    tank: "Standard Tank",
    img: "/products/2-15.jpg",
    features: ["RO + UV WATER PURIFIER WITH STORAGE"],
  },
  {
    name: "ZURIC BLACK",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO+UV",
    tank: "Standard Tank",
    img: "/products/2-16.jpg",
    features: ["RO + UV WATER PURIFIER WITH STORAGE"],
  },
  {
    name: "ZURIC WHITE",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO+UV",
    tank: "Standard Tank",
    img: "/products/2-17.jpg",
    features: ["RO + UV WATER PURIFIER WITH STORAGE"],
  },
  {
    name: "Aqua Roma Black",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹10000",
    mrp: null,
    liters: "Standard",
    stages: "RO+UV+UF",
    tank: "10L Tank",
    img: "/products/5-aqua-roma-blk.png",
    features: ["RO + UV + UF + TDS CONTROLER + ACTIVE COPPER/B12 ALKALINE FILTER"],
  },
  {
    name: "Aqua Roma White",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹10000",
    mrp: null,
    liters: "Standard",
    stages: "RO+UV+UF",
    tank: "10L Tank",
    img: "/products/6-aqua-roma-white.png",
    features: ["RO + UV + UF + TDS CONTROLER + ACTIVE COPPER/B12 ALKALINE FILTER"],
  },
  {
    name: "Alfa Transparent",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹11000",
    mrp: null,
    liters: "Standard",
    stages: "RO+UV",
    tank: "Standard Tank",
    img: "/products/64-alfa-transparent.jpg",
    features: ["RO + UV + TDS + UF WATER PURIFIER WITH STORAGE"],
  },
  {
    name: "Aqua Jade Blue",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹9500",
    mrp: null,
    liters: "Standard",
    stages: "RO+UV",
    tank: "Standard Tank",
    img: "/products/68-aqua-jade-blue.jpg",
    features: ["RO + UV WATER PURIFIER WITH STORAGE"],
  },
  {
    name: "Aqua Jade Sky Blue",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹9500",
    mrp: null,
    liters: "Standard",
    stages: "RO+UV",
    tank: "Standard Tank",
    img: "/products/69-aqua-jade-skyblue.jpg",
    features: ["RO + UV WATER PURIFIER WITH STORAGE"],
  },
  {
    name: "Aqua Jade Grey",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹9500",
    mrp: null,
    liters: "Standard",
    stages: "RO+UV",
    tank: "Standard Tank",
    img: "/products/70-aqua-jade-grey.jpg",
    features: ["RO + UV WATER PURIFIER WITH STORAGE"],
  },
  {
    name: "Aqua Jade Black",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹9500",
    mrp: null,
    liters: "Standard",
    stages: "RO+UV",
    tank: "Standard Tank",
    img: "/products/71-aqua-jade-black.jpg",
    features: ["RO + UV WATER PURIFIER WITH STORAGE"],
  },
  {
    name: "Aqua Jade Comrade Blue",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹9500",
    mrp: null,
    liters: "Standard",
    stages: "RO+UV",
    tank: "Standard Tank",
    img: "/products/72-aqua-jade-comrade-blue.jpg",
    features: ["RO + UV WATER PURIFIER WITH STORAGE"],
  },
  {
    name: "Aqua Grand +",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹10000",
    mrp: null,
    liters: "Standard",
    stages: "RO+UV",
    tank: "Standard Tank",
    img: "/products/73-aqua-grand-plus.jpg",
    features: ["RO + UV WATER PURIFIER WITH STORAGE"],
  },
  {
    name: "SS Domestic",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹16000",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/96-ss-domestic.jpg",
    features: ["RO Residential Water Purifier"],
  },
  {
    name: "Aqua Digi White",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹13000",
    mrp: null,
    liters: "15L/Hr",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/79-aqua-digi-white.jpg",
    features: ["RO+UV+UF+TDS CONTROLLER WITH LARGE STORAGE"],
  },
  {
    name: "Aqua Digi Black",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹13000",
    mrp: null,
    liters: "15L/Hr",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/79-a-aqua-digi-black.jpg",
    features: ["RO+UV+UF+TDS CONTROLLER WITH LARGE STORAGE"],
  },
  {
    name: "Aqua XL Blue",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹13000",
    mrp: null,
    liters: "15L/Hr",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/80-aqua-xl-blue.jpg",
    features: ["RO+UV+UF+TDS CONTROLLER WITH LARGE STORAGE"],
  },
  {
    name: "Aqua XL Black",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹13000",
    mrp: null,
    liters: "15L/Hr",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/81-aqua-xl-blk.jpg",
    features: ["RO+UV+UF+TDS CONTROLLER WITH LARGE STORAGE"],
  },
  {
    name: "Aqua Glory Blue",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹13000",
    mrp: null,
    liters: "15L/Hr",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/82-aqua-glory-blue.jpg",
    features: ["RO+UV+UF+TDS CONTROLLER WITH LARGE STORAGE"],
  },
  {
    name: "Aqua Glory Sky Blue",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹13000",
    mrp: null,
    liters: "15L/Hr",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/83-aqua-glory-skyblue.jpg",
    features: ["RO+UV+UF+TDS CONTROLLER WITH LARGE STORAGE"],
  },
  {
    name: "Aqua Glory Black",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹13000",
    mrp: null,
    liters: "15L/Hr",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/84-aqua-glory-black.jpg",
    features: ["RO+UV+UF+TDS CONTROLLER WITH LARGE STORAGE"],
  },
  {
    name: "Aqua Glory Full Black",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹13000",
    mrp: null,
    liters: "15L/Hr",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/85-aqua-glory-full-black.jpg",
    features: ["RO+UV+UF+TDS CONTROLLER WITH LARGE STORAGE"],
  },
  {
    name: "Aqua Pearl",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹13000",
    mrp: null,
    liters: "15L/Hr",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/86-aqua-pearl.jpg",
    features: ["RO+UV+UF+TDS CONTROLLER WITH LARGE STORAGE"],
  },
  {
    name: "Aqua Sonnet Blue",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹11000",
    mrp: null,
    liters: "15L/Hr",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/87-aqua-sonnet-blue.jpg",
    features: ["RO+UV+UF+TDS CONTROLLER WITH LARGE STORAGE"],
  },
  {
    name: "Aqua Sonnet Sky Blue",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹13000",
    mrp: null,
    liters: "15L/Hr",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/88-aqua-sonnet-sky-blue.jpg",
    features: ["RO+UV+UF+TDS CONTROLLER WITH LARGE STORAGE"],
  },
  {
    name: "Aqua Sonnet Black",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹13000",
    mrp: null,
    liters: "15L/Hr",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/89-aqua-sonnet-black.jpg",
    features: ["RO+UV+UF+TDS CONTROLLER WITH LARGE STORAGE"],
  },
  {
    name: "Aqua Sonnet Grey",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹13000",
    mrp: null,
    liters: "15L/Hr",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/90-aqua-sonnet-grey.jpg",
    features: ["RO+UV+UF+TDS CONTROLLER WITH LARGE STORAGE"],
  },
  {
    name: "Aqua Grand New",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹13000",
    mrp: null,
    liters: "15L/Hr",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/91-aqua-grand-new.jpg",
    features: ["RO+UV+UF+TDS CONTROLLER WITH LARGE STORAGE"],
  },
  {
    name: "Lexpure",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹11000",
    mrp: null,
    liters: "Standard",
    stages: "RO+UV",
    tank: "Standard Tank",
    img: "/products/92-lexpure.jpg",
    features: ["RO + UV WATER PURIFIER WITH STORAGE"],
  },
  {
    name: "Zetta Nova Star",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹13000",
    mrp: null,
    liters: "15L/Hr",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/95-zetta-nova-star.jpg",
    features: ["RO+UF+ALKALINE+TAV WATER PURIFIER WITH LARGE STORAGE", "FLOW PER HOUR-12 LTRS CONSUMPTION PER DAY 30-60 LTRS"],
  },
  {
    name: "Aqua X Thunder",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹13000",
    mrp: null,
    liters: "15L/Hr",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/97-aqua-x-thunder.jpg",
    features: ["RO+UV+UF+TDS CONTROLLER WITH LARGE STORAGE"],
  },
  {
    name: "Lexpure Seron +",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹13000",
    mrp: null,
    liters: "Standard",
    stages: "RO+UV",
    tank: "Standard Tank",
    img: "/products/101-lexpure-seron.jpg",
    features: ["RO + SN + AA + TDS WATER PURIFIER WITH STORAGE"],
  },
  {
    name: "Lexpure Olive",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹13000",
    mrp: null,
    liters: "Standard",
    stages: "RO+UV",
    tank: "Standard Tank",
    img: "/products/102-lexpure-olive.jpg",
    features: ["RO + SN + AA + TDS WATER PURIFIER WITH STORAGE"],
  },
  {
    name: "Aqua Pearl (Emerald Copper Technology)",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹13000",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/157-aqua-pearl.jpg",
    features: ["RO+UV+COPPER+ALKALINE"],
  },
  {
    name: "Prolife Fiesta Copper",
    brand: "PROLIFE",
    tag: "RO Systems",
    price: "₹16000",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/158-prolife.jpg",
    features: ["RO+UV+UF+TDS+COPPER WITH TOUCH SCREEN"],
  },
  {
    name: "AQUA EMERALD BLACK RO + UV",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/3-1.jpg",
    features: ["Under Sink RO System"],
  },
  {
    name: "AQUA NINE WHITE",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/3-2.jpg",
    features: ["Under Sink RO System"],
  },
  {
    name: "HOT AND COLD WAVE",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/3-3.jpg",
    features: ["Under Sink RO System"],
  },
  {
    name: "UNDER SINK RO MERLIN",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹16000",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/3-4.jpg",
    features: ["Under Sink RO System"],
  },
  {
    name: "UNDER SINK RO OLIVAR",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹14000",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/3-5.jpg",
    features: ["Under Sink RO System"],
  },
  {
    name: "UNDER SINK RO AQUA C3",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹14000",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/3-6.jpg",
    features: ["Under Sink RO System"],
  },
  {
    name: "UNDER SINK RO KENT EXCELL PLUS",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹20000",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/3-7.jpg",
    features: ["Under Sink RO System"],
  },
  {
    name: "UNDER SINK RO SYSTEM",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹12000",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/3-8.jpg",
    features: ["Under Sink RO System"],
  },
  {
    name: "Wave-4G-HOT AND COLD (RED)",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/3-9.jpg",
    features: ["Under Sink RO System"],
  },
  {
    name: "WAVE-4G-HOT-COLD (BLUE)",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Call for Price",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/3-10.jpg",
    features: ["Under Sink RO System"],
  },
  {
    name: "Aqua Guard Classic",
    brand: "AQUA GUARD",
    tag: "RO Systems",
    price: "₹11690",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/125-aqua-guard-classic.jpg",
    features: ["RO+UV  WATER PURIFIER WITH COPPER MAXX TECHNOLOGY"],
  },
  {
    name: "Aqua Guard Classic +",
    brand: "AQUA GUARD",
    tag: "RO Systems",
    price: "₹12990",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/126-aqua-guard-classic.jpg",
    features: ["UV  WATER PURIFIER WITH COPPER MAXX TECHNOLOGY"],
  },
  {
    name: "Aqua Guard Reviva Next RO",
    brand: "AQUA GUARD",
    tag: "RO Systems",
    price: "₹16190",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/127-aqua-guard-reviva-next.jpg",
    features: ["RO+UV E-BOILING+ACTIVE COPPER+MTDS+MINERAL GUARD TECHNOLOGY WATER PURIFIER"],
  },
  {
    name: "Aqua Guard Magna",
    brand: "AQUA GUARD",
    tag: "RO Systems",
    price: "₹21790",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/128-aqua-guard-magna.jpg",
    features: ["AQUA GUARD MAGNA RO+UV+MTDS TECHNOLOGY"],
  },
  {
    name: "Aqua Guard Enhance",
    brand: "AQUA GUARD",
    tag: "RO Systems",
    price: "₹21000",
    mrp: null,
    liters: "Standard",
    stages: "RO+UV",
    tank: "Standard Tank",
    img: "/products/147-a-aqua-sure-enhancer.jpg",
    features: ["RO + UV LED", "Active Copper Technology", "Mineral Guard Technology"],
  },
  {
    name: "Blue Star Regulas",
    brand: "BLUE STAR",
    tag: "RO Systems",
    price: "₹31000",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/136-blue-star-regauls.jpg",
    features: ["BLUE STAR REGAULS RO+UV+UF WITH HOT + ALKALINE"],
  },
  {
    name: "Blue Star Iconia",
    brand: "BLUE STAR",
    tag: "RO Systems",
    price: "₹18000",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/137-blue-star-iconia.jpg",
    features: ["ICONIA (HRRO+UV+UF+ALKALINE)"],
  },
  {
    name: "Blue Star Aristo",
    brand: "BLUE STAR",
    tag: "RO Systems",
    price: "₹11000",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/138-blue-star-aristo.jpg",
    features: ["AQUA GUARD MAGNA RO+UV+MTDS TECHNOLOGY"],
  },
  {
    name: "Blue Star Pristino",
    brand: "BLUE STAR",
    tag: "RO Systems",
    price: "₹8000",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/139-blue-star-pristina.jpg",
    features: ["UV WATER PURIFIER"],
  },
  {
    name: "Blue Star Genia Black",
    brand: "BLUE STAR",
    tag: "RO Systems",
    price: "₹11000",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/140-blue-star-genia-black.jpg",
    features: ["RO + UF WATER PURIFIER"],
  },
  {
    name: "Blue Star Genia White",
    brand: "BLUE STAR",
    tag: "RO Systems",
    price: "₹13000",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/141-blue-star-genia-white.jpg",
    features: ["RO + UF WATER PURIFIER"],
  },
  {
    name: "Blue Life Metro Plus",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹15490",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/142-blue-life-metro-plus.jpg",
    features: ["UF and UV Water Purifier"],
  },
  {
    name: "Blue Life Tulips Plus",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹16490",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/143-blue-life-tulips-plus.jpg",
    features: ["RO+UV Water Purifier"],
  },
  {
    name: "Blue Life Hygiene",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹14490",
    mrp: null,
    liters: "15L/Hr",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/144-blue-life-hygiene.jpg",
    features: ["RO Water Purifier"],
  },
  {
    name: "Blue Life Ripple Scientech (RO)",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹14949",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/145-blue-life-ripple-scientech.jpg",
    features: ["RO Water Purifier"],
  },
  {
    name: "Blue Life Ripple Scientech (RO+UV)",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹17460",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/146-blue-life-ripple-scientech.jpg",
    features: ["RO+UV Water Purifier"],
  },
  {
    name: "Blue Mount Elite Star",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹16000",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/133-blue-mount-elite-star.jpg",
    features: ["ALKALINE RO EVA ALKALINE RO WATER PURIFIER"],
  },
  {
    name: "Blue Mount Crown Star",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹14000",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/134-blue-mount-crown-star.jpg",
    features: ["ALKALINE RO + UF WATER PURIFIER"],
  },
  {
    name: "Kent Pearl Star",
    brand: "KENT",
    tag: "RO Systems",
    price: "₹21500",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/121-kent-pearl-star.jpg",
    features: ["RO+UV+UF+TDS Control process", "KENT WATER PURIFIER"],
  },
  {
    name: "Kent Crystal Alkaline",
    brand: "KENT",
    tag: "RO Systems",
    price: "₹21000",
    mrp: null,
    liters: "Standard",
    stages: "Multi Stage",
    tank: "Standard Tank",
    img: "/products/122-kent-crystal-alkaline.jpg",
    features: ["Premium quality", "Reliable performance"],
  },
  {
    name: "Kent Pearl",
    brand: "KENT",
    tag: "RO Systems",
    price: "₹20500",
    mrp: null,
    liters: "15L/Hr",
    stages: "RO+UV+UF",
    tank: "Standard Tank",
    img: "/products/123-kent-pearl.jpg",
    features: ["RO + UV + UF + TDS Control + Alkaline + UV in Tank Water Purifier"],
  },
  {
    name: "Kent Grand +",
    brand: "KENT",
    tag: "RO Systems",
    price: "₹21500",
    mrp: null,
    liters: "15L/Hr",
    stages: "RO+UV+UF",
    tank: "Standard Tank",
    img: "/products/124-kent-grand.jpg",
    features: ["RO + UV + UF + TDS Control  PROCESS"],
  },
  {
    name: "Livpure Glitz Silver",
    brand: "LIVPURE",
    tag: "RO Systems",
    price: "₹12000",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/129-livpure-glitz-silver.jpg",
    features: ["RO UF MINERALIZER 7 LTR RO WATER PURIFIER"],
  },
  {
    name: "Livpure Glitz Plus",
    brand: "LIVPURE",
    tag: "RO Systems",
    price: "₹10000",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/130-livpure-glitz-plus.jpg",
    features: ["RO UF MINERALIZER 7 LTR RO WATER PURIFIER"],
  },
  {
    name: "Livpure Bolt + Copper",
    brand: "LIVPURE",
    tag: "RO Systems",
    price: "₹15000",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/131-livpure-bolt-copper.jpg",
    features: ["RO+UF+MIN Water Purifier"],
  },
  {
    name: "Merlin Matrix White",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹16490",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/106-merlin-matrix-white.jpg",
    features: ["RO+ALK+UV+UF+TDS WATER PURIFIER"],
  },
  {
    name: "Merlin Matrix Black",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹16490",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/107-merlin-matrix-black.jpg",
    features: ["RO+ALK+UV+UF+TDS WATER PURIFIER"],
  },
  {
    name: "Merlin Planet Black",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹16490",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/108-merlin-planet-black.jpg",
    features: ["RO+ALK+UV+UF+TDS WATER PURIFIER"],
  },
  {
    name: "Merlin Planet White",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹16490",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/109-merlin-planet-white.jpg",
    features: ["RO+ALK+UV+UF+TASTE ADJUSTER WATER PURIFIER"],
  },
  {
    name: "Merlin Rapid Black",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹15990",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/110-merlin-rapid-black.jpg",
    features: ["RO+ALK+UV+UF+TASTE ADJUSTER WATER PURIFIER"],
  },
  {
    name: "Merlin Rapid White",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹15990",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/111-merlin-rapid-white.jpg",
    features: ["RO+ALK+UV+UF+TDS WATER PURIFIER"],
  },
  {
    name: "Merlin Rapid Lite",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹15490",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/112-merlin-rapid-lite.jpg",
    features: ["RO+ALK+UV+UF+TDS WATER PURIFIER"],
  },
  {
    name: "Merlin Alfa Black",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹15490",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/113-merlin-alfa-black.jpg",
    features: ["RO+ALK+UV+UF+TDS WATER PURIFIER"],
  },
  {
    name: "Merlin Planet Copper",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹16490",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/114-merlin-planet-copper.jpg",
    features: ["RO+ALK+UV+UF+TASTE ADJUSTER WATER PURIFIER"],
  },
  {
    name: "Aqua Sure Forbes Delight",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹11000",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "7L Tank",
    img: "/products/147-aqua-sure-forbs-delite.jpg",
    features: ["RO+UV WATER PURIFIER WITH STORAGE MODEL"],
  },
  {
    name: "Havells Digi Plus Alkaline",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹23000",
    mrp: null,
    liters: "15L/Hr",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/148-havells-digi-plus-alkaline.jpg",
    features: ["RO & UV Purified Alkaline Water"],
  },
  {
    name: "Philips UV Purifier",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹7500",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/149-philips-uv-purifier.jpg",
    features: ["UV PURIFIER WITH OUT STORAGE"],
  },
  {
    name: "AO Smith Pro Planet P4",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹23100",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/150-ao-smith-proplanet-p4.jpg",
    features: ["RO + SCMT + UV LED 5 Ltrs Water Purifier"],
  },
  {
    name: "AO Smith Pro Planet P7",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹32450",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/151-ao-smith-proplanet-p7.jpg",
    features: ["RO+SCMT 10 Ltrs Water Purifier"],
  },
  {
    name: "Faber C Guard",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹19900",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/152-faber-c-guard-ro-uv-mat-vit-c.jpg",
    features: ["RO + MAT Water Purifier"],
  },
  {
    name: "Pure It Hul",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹18000",
    mrp: null,
    liters: "Standard",
    stages: "RO+UV",
    tank: "Standard Tank",
    img: "/products/153-pureit-hul.jpg",
    features: ["Copper+ Mineral + RO + UV"],
  },
  {
    name: "LG RO",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹28290",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/154-lg-ro.jpg",
    features: ["(RO) Reverse Osmosis Water Purifier"],
  },
  {
    name: "Tago",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹8000",
    mrp: null,
    liters: "Standard",
    stages: "RO+UV",
    tank: "Standard Tank",
    img: "/products/3-tago.png",
    features: ["RO"],
  },
  {
    name: "Swan Ro",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹8000",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/4-swan-ro.png",
    features: ["MISTY SWAN RO"],
  },
  {
    name: "Wave Krystal",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹12000",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/7-wave-krystal.png",
    features: ["KRYSTAL AUTO TDS RO | UV | UF | COPPER"],
  },
  {
    name: "Genpure Ultima",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹11000",
    mrp: null,
    liters: "Standard",
    stages: "RO+UV",
    tank: "Standard Tank",
    img: "/products/8-genpure-ultima.png",
    features: ["RO + UV +TDS ADJUSTABLE"],
  },
  {
    name: "Wave Kombo",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹14000",
    mrp: null,
    liters: "Standard",
    stages: "RO+UV",
    tank: "Standard Tank",
    img: "/products/9-wave-kombo.png",
    features: ["WAVE KOMBO RO+UV"],
  },
  {
    name: "Chrome 1st Choise Model",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹16000",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/10-chrome.png",
    features: ["RO+ UV+ TDS+ UF+ COPPER FILTER CARTRIDGE"],
  },
  {
    name: "Org Todi",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹19000",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/11-org-todi.png",
    features: ["WATER PURIFIER TODI ALKLINATOR  PURIFICATION CAPACITY 15 LITER/HOUR"],
  },
  {
    name: "Wave 5G",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹21000",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/1-wave4g.png",
    features: ["HOT COLD & NORMAL ALKALINE WATER PURIFIER"],
  },
  {
    name: "No Bact",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹15000",
    mrp: null,
    liters: "Standard",
    stages: "Multi Stage",
    tank: "Standard Tank",
    img: "/products/2-no-bactt.png",
    features: ["(NORMAL + HOT)"],
  },
  {
    name: "Prolife Fiesta Full Black",
    brand: "PROLIFE",
    tag: "RO Systems",
    price: "₹16490",
    mrp: null,
    liters: "Standard",
    stages: "Multi Stage",
    tank: "Standard Tank",
    img: "/products/115-prolife-fiesta-full-black.jpg",
    features: ["Premium quality", "Reliable performance"],
  },
  {
    name: "Prolife Fiesta White",
    brand: "PROLIFE",
    tag: "RO Systems",
    price: "₹16490",
    mrp: null,
    liters: "Standard",
    stages: "Multi Stage",
    tank: "Standard Tank",
    img: "/products/116-prolife-fiesta-white.jpg",
    features: ["Premium quality", "Reliable performance"],
  },
  {
    name: "Prolife Fiesta Black Transparent",
    brand: "PROLIFE",
    tag: "RO Systems",
    price: "₹16490",
    mrp: null,
    liters: "Standard",
    stages: "Multi Stage",
    tank: "Standard Tank",
    img: "/products/117-prolife-fiesta-black-tranparent.jpg",
    features: ["Premium quality", "Reliable performance"],
  },
  {
    name: "Prolife Accent Alkaline",
    brand: "PROLIFE",
    tag: "RO Systems",
    price: "₹15490",
    mrp: null,
    liters: "Standard",
    stages: "Multi Stage",
    tank: "Standard Tank",
    img: "/products/118-prolife-accent-alkaline.jpg",
    features: ["Premium quality", "Reliable performance"],
  },
  {
    name: "Prolife Asta",
    brand: "PROLIFE",
    tag: "RO Systems",
    price: "₹15490",
    mrp: null,
    liters: "Standard",
    stages: "Multi Stage",
    tank: "Standard Tank",
    img: "/products/119-prolife-asta.jpg",
    features: ["Premium quality", "Reliable performance"],
  },
  {
    name: "Prolife Neon",
    brand: "PROLIFE",
    tag: "RO Systems",
    price: "₹15490",
    mrp: null,
    liters: "Standard",
    stages: "Multi Stage",
    tank: "Standard Tank",
    img: "/products/120-prolife-neon.jpg",
    features: ["Premium quality", "Reliable performance"],
  },
  {
    name: "25 LPH Skid",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹12500",
    mrp: null,
    liters: "25L/Hr",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/155-25-lph-skid.jpg",
    features: ["Fully Stainless Steel Body With 150 GPD High Performance Copper Winded Booster Pump. Purification : 25 Liter Per Hour , One 150 Gpd Booster Pump , Two Pices Membrane And One Activated Carbon Filter.Purification Technology : RO : Type : Electrical, Purification Stage :Stage 1: 5 microns inline PP filter || Stage 2: Granule Active Carbon Filter ||Stage 3: Block Active Carbon Filter || Stage 4: RO Membrane ||Stage 5: Post Carbon Filter.Max. Duty Cycle Per Day 100 Litre Suitable For Home , Office , Hotel , Restaurant, Cafe and Factory.Water Purifier System Which Run Upto 2000 TDS. Installation charges are 599 Installation provided by seller & charges Paid by customer (Customer Care No.18001202253) Chargeble After The Installation(Visit charge is 150-300).No Warranty for Filters, Filters are Consumables, Get Blocked or Choked Because of Water Only. If Water Quality is Good Filters Life will be More, If Water Quality is Bad (More Turbidity or More TDS) Filters Life will be Less. Our Excutive Will Solve Customer Problem Within 24 to 48 Hour.", "FLOW PER HOUR 25 LTRS", "PER DAY CONSUMPTION:70-130 LTRS", "Technician will be arranged once the product reaches to customer. For installation Customer has to pay Rs.400 to Rs.500 Extra to the technician depends on city and location. Kindly call on Toll-Free No.18001202253  to arrange the technician"],
  },
  {
    name: "25 LPH Double Pump",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹15000",
    mrp: null,
    liters: "25L/Hr",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/156-25-lph-double-pump.jpg",
    features: ["Fully Stainless Steel Body With 150 GPD High Performance Copper Winded Booster Pump. Purification : 25 Liter Per Hour , One 150 Gpd Booster Pump , Two Pices Membrane And One Activated Carbon Filter.Purification Technology : RO : Type : Electrical, Purification Stage :Stage 1: 5 microns inline PP filter || Stage 2: Granule Active Carbon Filter ||Stage 3: Block Active Carbon Filter || Stage 4: RO Membrane ||Stage 5: Post Carbon Filter.Max. Duty Cycle Per Day 100 Litre Suitable For Home , Office , Hotel , Restaurant, Cafe and Factory.Water Purifier System Which Run Upto 2000 TDS. Installation charges are 599 Installation provided by seller & charges Paid by customer (Customer Care No.18001202253) Chargeble After The Installation(Visit charge is 150-300).No Warranty for Filters, Filters are Consumables, Get Blocked or Choked Because of Water Only. If Water Quality is Good Filters Life will be More, If Water Quality is Bad (More Turbidity or More TDS) Filters Life will be Less. Our Excutive Will Solve Customer Problem Within 24 to 48 Hour.", "FLOW PER HOUR 25 LTRS", "PER DAY CONSUMPTION:70-130 LTRS", "Technician will be arranged once the product reaches to customer. For installation Customer has to pay Rs.400 to Rs.500 Extra to the technician depends on city and location. Kindly call on Toll-Free No.18001202253  to arrange the technician"],
  },
  {
    name: "25 LPH Whale",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹18000",
    mrp: null,
    liters: "25L/Hr",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/157-25-lph-whale.jpg",
    features: ["Fully Stainless Steel Body With 150 GPD High Performance Copper Winded Booster Pump. Purification : 25 Liter Per Hour , One 150 Gpd Booster Pump , Two Pices Membrane And One Activated Carbon Filter.Purification Technology : RO : Type : Electrical, Purification Stage :Stage 1: 5 microns inline PP filter || Stage 2: Granule Active Carbon Filter ||Stage 3: Block Active Carbon Filter || Stage 4: RO Membrane ||Stage 5: Post Carbon Filter.Max. Duty Cycle Per Day 100 Litre Suitable For Home , Office , Hotel , Restaurant, Cafe and Factory.Water Purifier System Which Run Upto 2000 TDS. Installation charges are 599 Installation provided by seller & charges Paid by customer (Customer Care No.18001202253) Chargeble After The Installation(Visit charge is 150-300).No Warranty for Filters, Filters are Consumables, Get Blocked or Choked Because of Water Only. If Water Quality is Good Filters Life will be More, If Water Quality is Bad (More Turbidity or More TDS) Filters Life will be Less. Our Excutive Will Solve Customer Problem Within 24 to 48 Hour.", "FLOW PER HOUR 25 LTRS", "PER DAY CONSUMPTION:70-130 LTRS", "Technician will be arranged once the product reaches to customer. For installation Customer has to pay Rs.400 to Rs.500 Extra to the technician depends on city and location. Kindly call on Toll-Free No.18001202253  to arrange the technician"],
  },
  {
    name: "50 LPH Plant",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹28000",
    mrp: null,
    liters: "50L/Hr",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/158-50-lph-plant.jpg",
    features: ["Drink pure water for a healthy life.||Purification Technology : RO : Type : Electrical, Purification Stage :Stage 1: 5 microns inline PP filter || Stage 2: Granule Active Carbon Filter ||Stage 3: Block Active Carbon Filter || Stage 4: RO Membrane ||Stage 5: Post Carbon Filter.Fully automatic RO water purifier  Stainless Steel Body With Two 150 GPD high-performance copper winding motor. RO Water Purifier System Which runs up to 2000 TDS level of Input Water from Both Ground water and Munciple Supply. Purification Capacity: 50 Liter Per Hour,2 pcs 150 Gpd Booster Pump, 4 pcs membrane. Max. duty cycle per day: 200 To 300 Ltr,Suitable for Office, Restaurant, Cafe, Resort and Factory. This water purifier has a capacity of 50 Ltr, so as to ensure continuous supply of purified water even when there is no electricity or running tap water. After The Installation(Visit charge is 250-300).No Warranty for Filters, Filters are Consumables, Get Blocked or Choked Because of Water Only. If Water Quality is Good Filters Life will be More, If Water Quality is (More Turbidity or More TDS) Filters Life will be Less. Our Excutive Will Solve Customer Problem Within 24 to 48 Hour.", "Technician will be arranged once the product reaches to customer. For installation Customer has to pay Rs.400 to Rs.500 Extra to the technician depends on city and location. Kindly call on Toll-Free No.18001202253  to arrange the technician"],
  },
  {
    name: "100 LPH Plant",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹43000",
    mrp: null,
    liters: "100L/Hr",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/159-100-lph-plant.jpg",
    features: ["Fully Stainless Steel Body With Two 300 GPD High Performance Copper Winded Booster Pump", "Fully automatic RO water purifier with Auto Shut Off Function || Purification Technology : RO : Type : Electrical, Purification Stage :Stage 1: 5 microns inline PP filter || Stage 2: Granule Active Carbon Filter ||Stage 3: Block Active Carbon Filter || Stage 4: RO Membrane ||Stage 5: Post UV Filter", "Max. Duty Cycle Per Day500 - 700 Litre Suitable For Home , Office , Hotel , Restaurant, Cafe and Factory", "Purification : 100 Liter Per Hour , Two 300 Gpd Booster Pump , Four Pices Membrane 150 GPD And One Activated Carbon Filter"],
  },
  {
    name: "250 LPH Plant",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹110000",
    mrp: null,
    liters: "Standard",
    stages: "Multi Stage",
    tank: "Standard Tank",
    img: "/products/160-250-lph-plant.jpg",
    features: ["Premium quality", "Reliable performance"],
  },
  {
    name: "500 LPH Plant",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "₹160000",
    mrp: null,
    liters: "Standard",
    stages: "Multi Stage",
    tank: "Standard Tank",
    img: "/products/161-500-lph-plant.jpg",
    features: ["Premium quality", "Reliable performance"],
  },
  {
    name: "Desire Plus",
    brand: "AQUA CARE",
    tag: "Our Products",
    price: "60CM & 90CM",
    mrp: null,
    liters: "Standard",
    stages: "Multi Stage",
    tank: "Standard Tank",
    img: "/products/desire-plus.jpg",
    features: ["Premium quality", "Reliable performance"],
  },
  {
    name: "Reflection Plus",
    brand: "AQUA CARE",
    tag: "Our Products",
    price: "60CM & 90CM",
    mrp: null,
    liters: "Standard",
    stages: "Multi Stage",
    tank: "Standard Tank",
    img: "/products/reflection-plus.jpg",
    features: ["Premium quality", "Reliable performance"],
  },
  {
    name: "Rhino Plus",
    brand: "AQUA CARE",
    tag: "Our Products",
    price: "60CM",
    mrp: null,
    liters: "Standard",
    stages: "Multi Stage",
    tank: "Standard Tank",
    img: "/products/rhino-plus.jpg",
    features: ["Premium quality", "Reliable performance"],
  },
  {
    name: "Rhino",
    brand: "AQUA CARE",
    tag: "Our Products",
    price: "60CM",
    mrp: null,
    liters: "Standard",
    stages: "Multi Stage",
    tank: "Standard Tank",
    img: "/products/rhino.jpg",
    features: ["Premium quality", "Reliable performance"],
  },
];

export const AMC_PLANS: AmcPlanItem[] = [
  {
    name: "Silver",
    price: "₹999",
    period: "/year",
    color: "from-slate-400 to-slate-600",
    features: ["2 Preventive Services", "Filter Check", "Phone Support", "10% Parts Discount"],
  },
  {
    name: "Gold",
    price: "₹1,999",
    period: "/year",
    color: "from-amber-400 to-yellow-600",
    highlight: true,
    features: ["4 Preventive Services", "1 Free Filter Set", "Priority Support", "20% Parts Discount", "Free Emergency Visit"],
  },
  {
    name: "Platinum",
    price: "₹3,499",
    period: "/year",
    color: "from-cyan-500 to-blue-600",
    features: ["6 Preventive Services", "All Filters Included", "24/7 Support", "Free All Parts", "Free Emergency Visit", "Annual Deep Clean"],
  },
];

export const TESTIMONIALS: TestimonialItem[] = [
  {
    name: "Rajesh Kumar",
    loc: "Karur",
    stars: 5,
    text: "Excellent service! My RO purifier was installed within hours. The water quality is fantastic. Highly recommend Aqua Care to everyone.",
  },
  {
    name: "Priya Lakshmi",
    loc: "Kulithalai",
    stars: 5,
    text: "Solar water heater எடுத்தோம். மாதம் ₹800 மிச்சமாகிறது. Perfect installation and after-sales support. 5 stars!",
  },
  {
    name: "Mohammed Farooq",
    loc: "Tiruchirappalli",
    stars: 5,
    text: "Best AMC plan in the region. They come on time, professional staff, and genuine spare parts. Trust them completely.",
  },
  {
    name: "Kavitha Devi",
    loc: "Aravakurichi",
    stars: 5,
    text: "Washing machine repair was done same day. Technician explained the problem clearly. Very transparent pricing. Great experience!",
  },
];

export const WHY_CHOOSE_POINTS: WhyChoosePoint[] = [
  { icon: Clock, title: "Same-Day Service", desc: "Book before noon, get service today" },
  { icon: Award, title: "Certified Technicians", desc: "Factory-trained, background-verified" },
  { icon: Shield, title: "Genuine Parts", desc: "100% authentic spare parts only" },
  { icon: ThumbsUp, title: "Price Transparency", desc: "No hidden charges, ever" },
];

export const BOOKING_STEPS: BookingStep[] = [
  { step: "01", title: "Call or WhatsApp Us", desc: "Reach us anytime between 8 AM – 8 PM" },
  { step: "02", title: "Schedule a Visit", desc: "Pick a time slot that works for you" },
  { step: "03", title: "Expert Arrives", desc: "Certified technician at your doorstep" },
];

export const CONTACT_CARDS: ContactChannelCard[] = [
  {
    icon: "phone",
    title: "Call Us",
    lines: [PHONE_DISPLAY, "Mon–Sun: 8 AM – 8 PM"],
    link: CALL,
    label: "Call Now",
    color: "from-cyan-500 to-blue-600",
  },
  {
    icon: "message",
    title: "WhatsApp",
    lines: ["Chat with us 24/7", "Quick response guaranteed"],
    link: WHATSAPP,
    label: "Open WhatsApp",
    color: "from-green-500 to-emerald-600",
  },
  {
    icon: "map",
    title: "Visit Us",
    lines: [...ADDRESS_LINES],
    link: MAPS_DIRECTIONS_URL,
    label: "Get Directions",
    color: "from-orange-500 to-red-500",
  },
];

export const FOOTER_SERVICE_LINKS: FooterServiceLink[] = SERVICES.map((s) => ({
  label: s.title,
  href: `/services/${s.slug}`,
}));
