import {
  Droplets,
  Sun,
  Wrench,
  Shield,
  Clock,
  Award,
  Zap,
  ThumbsUp,
  CheckCircle,
  Waves,
  Refrigerator,
  WashingMachine,
} from "lucide-react";
import { ADDRESS_LINES, CALL, MAPS_DIRECTIONS_URL, PHONE_DISPLAY, WHATSAPP } from "./constants";
import type {
  AmcPlanItem,
  BookingStep,
  ContactChannelCard,
  FooterServiceLink,
  HeroFeatureCard,
  ProductItem,
  ProductCategory,
  ServiceItem,
  StatItem,
  TestimonialItem,
  TrustItem,
  WhyChoosePoint,
} from "./types";

export const STATS: StatItem[] = [
  { val: "12+", label: "Years Experience" },
  { val: "8,500+", label: "Happy Customers" },
  { val: "15,000+", label: "Services Done" },
  { val: "98%", label: "Satisfaction Rate" },
];

export const HERO_FEATURE_CARDS: HeroFeatureCard[] = [
  { icon: Droplets, title: "RO Purifiers", sub: "Contact for Quote", color: "from-cyan-500 to-blue-600" },
  { icon: Sun, title: "Solar Systems", sub: "Save 80% Bills", color: "from-amber-500 to-orange-500" },
  { icon: Shield, title: "AMC Plans", sub: "Custom Maintenance", color: "from-teal-500 to-cyan-600" },
  { icon: Wrench, title: "Same-Day Service", sub: "All Brands", color: "from-blue-600 to-indigo-600" },
];

export const TRUST_ITEMS: TrustItem[] = [
  { icon: Award, text: "ISO Certified" },
  { icon: ThumbsUp, text: "MNRE Empanelled" },
  { icon: Shield, text: "Genuine Spare Parts" },
  { icon: Clock, text: "Same-Day Service" },
  { icon: CheckCircle, text: "2-Year Warranty" },
];

export const SERVICES: ServiceItem[] = [
  {
    slug: "ro-water-purifier",
    icon: Droplets,
    title: "RO Water Purifiers",
    tamil: "RO நீர் சுத்திகரிப்பு",
    desc: "Premium multi-stage filtration systems for pure, safe drinking water for your family.",
    color: "from-cyan-500 to-blue-600",
  },
  {
    slug: "ro-service",
    icon: Wrench,
    title: "RO Service & Repair",
    tamil: "சேவை & பழுது",
    desc: "Expert technicians for same-day service, filter replacement, and complete overhaul.",
    color: "from-blue-500 to-indigo-600",
  },
  {
    slug: "amc",
    icon: Shield,
    title: "AMC Plans",
    tamil: "வருடாந்திர பராமரிப்பு",
    desc: "Comprehensive annual maintenance contracts with priority support and free filters.",
    color: "from-teal-500 to-cyan-600",
  },
  {
    slug: "solar-water-heater",
    icon: Sun,
    title: "Solar Water Heater",
    tamil: "சோலார் வாட்டர் ஹீட்டர்",
    desc: "High-efficiency solar thermal systems. Cut electricity bills by up to 80%.",
    color: "from-amber-500 to-orange-500",
  },
  {
    slug: "solar-panel",
    icon: Zap,
    title: "Solar Panel Installation",
    tamil: "சோலார் பேனல்",
    desc: "Grid-tie and off-grid photovoltaic systems with MNRE-certified installations.",
    color: "from-yellow-500 to-amber-600",
  },
  {
    slug: "water-softener",
    icon: Waves,
    title: "Water Softener",
    tamil: "வாட்டர் சாஃப்டனர்",
    desc: "Ion-exchange softening systems that protect appliances and skin from hard water.",
    color: "from-sky-500 to-blue-500",
  },
  {
    slug: "fridge-repair",
    icon: Refrigerator,
    title: "Fridge Repair",
    tamil: "குளிர்சாதனப் பெட்டி பழுது",
    desc: "All brands. Gas refilling, compressor, thermostat, and door seal repairs.",
    color: "from-blue-600 to-violet-600",
  },
  {
    slug: "washing-machine-repair",
    icon: WashingMachine,
    title: "Washing Machine Repair",
    tamil: "வாஷிங் மெஷின் பழுது",
    desc: "Top-load & front-load specialists. Motor, drum, PCB and pump repairs.",
    color: "from-indigo-500 to-blue-600",
  },
];



export const PRODUCT_CATEGORIES: ProductCategory[] = [
  { id: "domestic-ro", title: "Domestic RO", slug: "domestic-ro", description: "Premium RO purifiers for your home." },
  { id: "commercial-ro", title: "Commercial RO Plants", slug: "commercial-ro", description: "High-capacity RO plants for offices and institutions." },
  { id: "industrial", title: "Industrial Water Systems", slug: "industrial", description: "Heavy-duty water systems for industrial use." },
  { id: "dispensers", title: "Water Dispensers", slug: "dispensers", description: "Hot, cold, and normal water dispensers." },
  { id: "solar", title: "Solar Water Heaters", slug: "solar", description: "Energy-efficient solar water heating systems." },
  { id: "softeners", title: "Water Softeners", slug: "softeners", description: "Protect appliances and skin from hard water." },
  { id: "accessories", title: "Accessories", slug: "accessories", description: "Spares and accessories for water systems." },
];

export const PRODUCTS: ProductItem[] = [
  {
    name: "Aqua Shark",
    brand: "YUVANTHIKA AQUACARE",
    tag: "Best Seller",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "8L Tank",
    img: "/products/7-wave-krystal.webp",
    features: ["Alkaline RO purifier", "Auto on/off function", "Antibacterial tank", "Wall/table top mount"],
    categoryId: "domestic-ro",
    featured: true},
  {
    name: "Blue Rock",
    brand: "YUVANTHIKA AQUACARE",
    tag: "TDS Control",
    price: "Contact Us",
    mrp: null,
    liters: "18L/Hr",
    stages: "6 Stage",
    tank: "8L Tank",
    img: "/products/86-aqua-pearl.webp",
    features: ["Fully automatic service", "TDS controller", "Water scale indicator", "Computer controlled operation"],
    categoryId: "domestic-ro",
    featured: true},
  {
    name: "Aqua Angel",
    brand: "YUVANTHIKA AQUACARE",
    tag: "Alkaline",
    price: "Contact Us",
    mrp: null,
    liters: "18L/Hr",
    stages: "7 Stage",
    tank: "10L Tank",
    img: "/products/11-water-lilly-blue.webp",
    features: ["Detachable washable tank", "LED indicator panel", "Anti-bacterial coating", "Voltage spike protection"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Aqua Zebra",
    brand: "YUVANTHIKA AQUACARE",
    tag: "Alkaline RO",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "9 Stage",
    tank: "10L Tank",
    img: "/products/12-water-lilly-skyblue.webp",
    features: ["Anti-oxidant alkaline water", "LED indicator", "Detachable washable tank", "TDS mineral technology"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Crown Star",
    brand: "BLUE MOUNT",
    tag: "Most Advanced",
    price: "Contact Us",
    mrp: null,
    liters: "18L/Hr",
    stages: "12 Stage",
    tank: "12L Tank",
    img: "/products/134-blue-mount-crown-star.webp",
    features: ["12-stage purification", "Anti-oxidant alkaline tech", "Fully automatic service", "Computer controlled operation"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Yuvanthika Tulips",
    brand: "YUVANTHIKA AQUACARE",
    tag: "Steel Body",
    price: "Contact Us",
    mrp: null,
    liters: "18L/Hr",
    stages: "12 Stage",
    tank: "9L Tank",
    img: "/products/143-blue-life-tulips-plus.webp",
    features: ["304 grade stainless steel", "Anti-oxidant alkaline water", "Detachable washable tank", "Fully automatic service"],
    categoryId: "domestic-ro",
    featured: true},
  {
    name: "Whale RO + UF",
    brand: "WHALE",
    tag: "Family Size",
    price: "Contact Us",
    mrp: null,
    liters: "25L Tank",
    stages: "RO + UF",
    tank: "25L Tank",
    img: "/products/157-25-lph-whale.webp",
    features: ["Extra large 25L storage", "Dual RO + UF purification", "Ideal for large families", "Modern designer look"],
    categoryId: "domestic-ro",
    featured: true},
  {
    name: "AQUA  RAGA 2090 RUBY PINK",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/1-1.webp",
    features: ["RO membrane purification, handles up to 2000 TDS", "12 litres/hr output, fills 10L in ~1 hour", "Auto shut-off when tank is full", "Food grade ABS plastic body", "Input: 150V–270V AC, booster pump included"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "AQUA 2090 BLUE",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/1-2.webp",
    features: ["RO membrane purification, handles up to 2000 TDS", "12 litres/hr output, fills 10L in ~1 hour", "Auto shut-off when tank is full", "Food grade ABS plastic body", "Input: 150V–270V AC, booster pump included"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "AQUA 2090 DEEP PURPLE",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/1-3.webp",
    features: ["RO membrane purification, handles up to 2000 TDS", "12 litres/hr output, fills 10L in ~1 hour", "Auto shut-off when tank is full", "Food grade ABS plastic body", "Input: 150V–270V AC, booster pump included"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "AQUA 2090 GREEN",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/1-4.webp",
    features: ["RO membrane purification, handles up to 2000 TDS", "12 litres/hr output, fills 10L in ~1 hour", "Auto shut-off when tank is full", "Food grade ABS plastic body", "Input: 150V–270V AC, booster pump included"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "AQUA 2090 MIRROR BLACK",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/1-5.webp",
    features: ["RO membrane purification, handles up to 2000 TDS", "12 litres/hr output, fills 10L in ~1 hour", "Auto shut-off when tank is full", "Food grade ABS plastic body", "Input: 150V–270V AC, booster pump included"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "AQUA RAGA 2090 DAYTONA SILVER",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/1-6.webp",
    features: ["RO membrane purification, handles up to 2000 TDS", "12 litres/hr output, fills 10L in ~1 hour", "Auto shut-off when tank is full", "Food grade ABS plastic body", "Input: 150V–270V AC, booster pump included"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "AQUA RAGA 2090 HERITAGE GOLD",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/1-7.webp",
    features: ["RO membrane purification, handles up to 2000 TDS", "12 litres/hr output, fills 10L in ~1 hour", "Auto shut-off when tank is full", "Food grade ABS plastic body", "Input: 150V–270V AC, booster pump included"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "AQUA RAGA 2090 ROLEX GREEN",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/1-8.webp",
    features: ["RO membrane purification, handles up to 2000 TDS", "12 litres/hr output, fills 10L in ~1 hour", "Auto shut-off when tank is full", "Food grade ABS plastic body", "Input: 150V–270V AC, booster pump included"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "AQUA RAGA 2090 SIERRA BLUE",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/1-9.webp",
    features: ["RO membrane purification, handles up to 2000 TDS", "12 litres/hr output, fills 10L in ~1 hour", "Auto shut-off when tank is full", "Food grade ABS plastic body", "Input: 150V–270V AC, booster pump included"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "AQUA ROMA CHERRY SILVER",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/1-10.webp",
    features: ["RO membrane purification, handles up to 2000 TDS", "12 litres/hr output, fills 10L in ~1 hour", "Auto shut-off when tank is full", "Food grade ABS plastic body", "Input: 150V–270V AC, booster pump included"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "AQUA ROMA METALIC BLUE",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/1-11.webp",
    features: ["RO membrane purification, handles up to 2000 TDS", "12 litres/hr output, fills 10L in ~1 hour", "Auto shut-off when tank is full", "Food grade ABS plastic body", "Input: 150V–270V AC, booster pump included"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "AQUA ROMA METALLIC GREEN",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/1-12.webp",
    features: ["RO membrane purification, handles up to 2000 TDS", "12 litres/hr output, fills 10L in ~1 hour", "Auto shut-off when tank is full", "Food grade ABS plastic body", "Input: 150V–270V AC, booster pump included"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "AQUA ROMA WHTE",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/1-13.webp",
    features: ["RO membrane purification, handles up to 2000 TDS", "12 litres/hr output, fills 10L in ~1 hour", "Auto shut-off when tank is full", "Food grade ABS plastic body", "Input: 150V–270V AC, booster pump included"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "AQUA V5 BLACK",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/1-14.webp",
    features: ["RO membrane purification, handles up to 2000 TDS", "12 litres/hr output, fills 10L in ~1 hour", "Auto shut-off when tank is full", "Food grade ABS plastic body", "Input: 150V–270V AC, booster pump included"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "AQUA V5 BLUE",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/1-15.webp",
    features: ["RO membrane purification, handles up to 2000 TDS", "12 litres/hr output, fills 10L in ~1 hour", "Auto shut-off when tank is full", "Food grade ABS plastic body", "Input: 150V–270V AC, booster pump included"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "AQUA V5 GREY",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/1-16.webp",
    features: ["RO membrane purification, handles up to 2000 TDS", "12 litres/hr output, fills 10L in ~1 hour", "Auto shut-off when tank is full", "Food grade ABS plastic body", "Input: 150V–270V AC, booster pump included"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "AQUA V5 MAROON",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/1-17.webp",
    features: ["RO membrane purification, handles up to 2000 TDS", "12 litres/hr output, fills 10L in ~1 hour", "Auto shut-off when tank is full", "Food grade ABS plastic body", "Input: 150V–270V AC, booster pump included"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "EMIRA BLACK",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/1-18.webp",
    features: ["RO membrane purification, handles up to 2000 TDS", "12 litres/hr output, fills 10L in ~1 hour", "Auto shut-off when tank is full", "Food grade ABS plastic body", "Input: 150V–270V AC, booster pump included"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "EMIRA CHERRY RED",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/1-19.webp",
    features: ["RO membrane purification, handles up to 2000 TDS", "12 litres/hr output, fills 10L in ~1 hour", "Auto shut-off when tank is full", "Food grade ABS plastic body", "Input: 150V–270V AC, booster pump included"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "EMIRA WHITE",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/1-20.webp",
    features: ["RO membrane purification, handles up to 2000 TDS", "12 litres/hr output, fills 10L in ~1 hour", "Auto shut-off when tank is full", "Food grade ABS plastic body", "Input: 150V–270V AC, booster pump included"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "HI FLO CHERRY RED",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/1-21.webp",
    features: ["RO membrane purification, handles up to 2000 TDS", "12 litres/hr output, fills 10L in ~1 hour", "Auto shut-off when tank is full", "Food grade ABS plastic body", "Input: 150V–270V AC, booster pump included"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "HI FLO METALLIC GREY",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/1-22.webp",
    features: ["RO membrane purification, handles up to 2000 TDS", "12 litres/hr output, fills 10L in ~1 hour", "Auto shut-off when tank is full", "Food grade ABS plastic body", "Input: 150V–270V AC, booster pump included"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "HI FLO METTALIC BLACK",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/1-23.webp",
    features: ["RO membrane purification, handles up to 2000 TDS", "12 litres/hr output, fills 10L in ~1 hour", "Auto shut-off when tank is full", "Food grade ABS plastic body", "Input: 150V–270V AC, booster pump included"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "HI FLO SKY BLUE",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/1-24.webp",
    features: ["RO membrane purification, handles up to 2000 TDS", "12 litres/hr output, fills 10L in ~1 hour", "Auto shut-off when tank is full", "Food grade ABS plastic body", "Input: 150V–270V AC, booster pump included"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "HI FLO STD BLUE",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/1-25.webp",
    features: ["RO membrane purification, handles up to 2000 TDS", "12 litres/hr output, fills 10L in ~1 hour", "Auto shut-off when tank is full", "Food grade ABS plastic body", "Input: 150V–270V AC, booster pump included"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "LEXZON AQUA BLUE",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/1-26.webp",
    features: ["RO membrane purification, handles up to 2000 TDS", "12 litres/hr output, fills 10L in ~1 hour", "Auto shut-off when tank is full", "Food grade ABS plastic body", "Input: 150V–270V AC, booster pump included"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "LEXZON AQUA GREEN",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/1-27.webp",
    features: ["RO membrane purification, handles up to 2000 TDS", "12 litres/hr output, fills 10L in ~1 hour", "Auto shut-off when tank is full", "Food grade ABS plastic body", "Input: 150V–270V AC, booster pump included"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "LEXZON GREY",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/1-28.webp",
    features: ["RO membrane purification, handles up to 2000 TDS", "12 litres/hr output, fills 10L in ~1 hour", "Auto shut-off when tank is full", "Food grade ABS plastic body", "Input: 150V–270V AC, booster pump included"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "LEXZON METTALIC BLUE",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/1-29.webp",
    features: ["RO membrane purification, handles up to 2000 TDS", "12 litres/hr output, fills 10L in ~1 hour", "Auto shut-off when tank is full", "Food grade ABS plastic body", "Input: 150V–270V AC, booster pump included"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "LX ONE AURORA RED",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/1-30.webp",
    features: ["RO membrane purification, handles up to 2000 TDS", "12 litres/hr output, fills 10L in ~1 hour", "Auto shut-off when tank is full", "Food grade ABS plastic body", "Input: 150V–270V AC, booster pump included"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "LX ONE CHARCOAL BLACK",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/1-31.webp",
    features: ["RO membrane purification, handles up to 2000 TDS", "12 litres/hr output, fills 10L in ~1 hour", "Auto shut-off when tank is full", "Food grade ABS plastic body", "Input: 150V–270V AC, booster pump included"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "LX ONE GUN METAL",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/1-32.webp",
    features: ["RO membrane purification, handles up to 2000 TDS", "12 litres/hr output, fills 10L in ~1 hour", "Auto shut-off when tank is full", "Food grade ABS plastic body", "Input: 150V–270V AC, booster pump included"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "LX ONE POLAR WHITE",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/1-33.webp",
    features: ["RO membrane purification, handles up to 2000 TDS", "12 litres/hr output, fills 10L in ~1 hour", "Auto shut-off when tank is full", "Food grade ABS plastic body", "Input: 150V–270V AC, booster pump included"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "LX ONE WHITE GOLD",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/1-34.webp",
    features: ["RO membrane purification, handles up to 2000 TDS", "12 litres/hr output, fills 10L in ~1 hour", "Auto shut-off when tank is full", "Food grade ABS plastic body", "Input: 150V–270V AC, booster pump included"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "PUROSIS COPPER GOLD",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/1-35.webp",
    features: ["RO membrane purification, handles up to 2000 TDS", "12 litres/hr output, fills 10L in ~1 hour", "Auto shut-off when tank is full", "Food grade ABS plastic body", "Input: 150V–270V AC, booster pump included"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Wallmount",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/1-wallmount.webp",
    features: ["RO membrane purification, handles up to 2000 TDS", "12 litres/hr output, fills 10L in ~1 hour", "Auto shut-off when tank is full", "Food grade ABS plastic body", "Input: 150V–270V AC, booster pump included"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Dolphin",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "10L Tank",
    img: "/products/2dolphin.webp",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
    categoryId: "commercial-ro",
    featured: true},
  {
    name: "Dolphin Red",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "10L Tank",
    img: "/products/2c-dolphin-red.webp",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
    categoryId: "commercial-ro",
    featured: false},
  {
    name: "Dolphin Black",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "10L Tank",
    img: "/products/2a-dolphin-black.webp",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
    categoryId: "commercial-ro",
    featured: false},
  {
    name: "Dolphin Grey",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "10L Tank",
    img: "/products/2b-dolphin-gray.webp",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
    categoryId: "commercial-ro",
    featured: false},
  {
    name: "H2O Black",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "10L Tank",
    img: "/products/3-h2o-black.webp",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "H2O Red",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "10L Tank",
    img: "/products/4-h2o-red.webp",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Aqua Touch Black",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "10L Tank",
    img: "/products/aqua-touch-black.webp",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Aqua Touch Red",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "10L Tank",
    img: "/products/6-aqua-touch-red.webp",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Aqua Touch Grey",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "10L Tank",
    img: "/products/aqua-touch-greychange.webp",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Aqua Touch Blue",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "10L Tank",
    img: "/products/8-aqua-touch-blue.webp",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "AQUA TOUCH COMRADE BLUE",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "10L Tank",
    img: "/products/aqua-touch-comrade-bluechange.webp",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Aqua Touch Skyblue",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "10L Tank",
    img: "/products/10-aqua-touch-sky-blue.webp",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Water Lilly Blue",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "10L Tank",
    img: "/products/11-water-lilly-blue.webp",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Water Lilly Comrade Blue",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "10L Tank",
    img: "/products/water-lilly-comrade-bluechange.webp",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Water Lilly Sky Blue",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "10L Tank",
    img: "/products/12-water-lilly-skyblue.webp",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Water Lilly Black",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "10L Tank",
    img: "/products/water-lilly-blackchange.webp",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Water Lilly Grey",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "10L Tank",
    img: "/products/15-water-lilly-grey.webp",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Water Lilly Red",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "10L Tank",
    img: "/products/water-lilly-redchange.webp",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Apple Black",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "10L Tank",
    img: "/products/28-apple-black.webp",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Apple Blue",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "10L Tank",
    img: "/products/29-apple-blue.webp",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Aqua Lio Blue",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "10L Tank",
    img: "/products/31-aqua-lio-blue.webp",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Aqua Lio Black",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "10L Tank",
    img: "/products/aqua-lio-bluechange.webp",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Aqua Lio Sky Blue",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "10L Tank",
    img: "/products/32-aqua-lio-skyblue.webp",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Aqua Mars Blue",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "10L Tank",
    img: "/products/33-aqua-mars-blue.webp",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Aqua Mars Sky Blue",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "10L Tank",
    img: "/products/34-aqua-mars-green.webp",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Aqua Mars Grey",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "10L Tank",
    img: "/products/35-aqua-mars-grey.webp",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Aqua Mars Black",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "10L Tank",
    img: "/products/36-aqua-mars-black.webp",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Aqua Mars Stone Badge",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "10L Tank",
    img: "/products/37-aqua-mars-stone-badge.webp",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Aqua Glance",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "10L Tank",
    img: "/products/38-aqua-glance.webp",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "A Star Blue",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "10L Tank",
    img: "/products/39a-star-blue.webp",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Water Pia Blue",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "10L Tank",
    img: "/products/41-water-pia-blue.webp",
    features: ["Ro water purifier with storage", "Flow rate per hour 12 ltrs", "Per day consumption 30 to 60 ltrs"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "AQUA FLIP BLUE",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "RO+UV",
    tank: "Wall Mount",
    img: "/products/2-1.webp",
    features: ["RO + UV WATER PURIFIER WITH STORAGE"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "AQUA FLIP GREEN",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "RO+UV",
    tank: "Wall Mount",
    img: "/products/2-2.webp",
    features: ["RO + UV WATER PURIFIER WITH STORAGE"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "AQUA FLIP",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "RO+UV",
    tank: "Wall Mount",
    img: "/products/2-3.webp",
    features: ["RO + UV WATER PURIFIER WITH STORAGE"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "AQUA INNOVICA AQUA GREEN",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "RO+UV",
    tank: "Wall Mount",
    img: "/products/2-4.webp",
    features: ["RO + UV WATER PURIFIER WITH STORAGE"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "AQUA INNOVICA CANDY WHITE BLUE",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "RO+UV",
    tank: "Wall Mount",
    img: "/products/2-5.webp",
    features: ["RO + UV WATER PURIFIER WITH STORAGE"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "AQUA INNOVICA METTALIC ENERGY BLUE",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "RO+UV",
    tank: "Wall Mount",
    img: "/products/2-6.webp",
    features: ["RO + UV WATER PURIFIER WITH STORAGE"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "AQUA INNOVICA METTALIC STEEL GREY",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "RO+UV",
    tank: "Wall Mount",
    img: "/products/2-7.webp",
    features: ["RO + UV WATER PURIFIER WITH STORAGE"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "AQUA INNOVICA MIRROR BLACK",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "RO+UV",
    tank: "Wall Mount",
    img: "/products/2-8.webp",
    features: ["RO + UV WATER PURIFIER WITH STORAGE"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "LX TWO ADMIRAL BLUE",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "RO+UV",
    tank: "Wall Mount",
    img: "/products/2-9.webp",
    features: ["RO + UV WATER PURIFIER WITH STORAGE"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "LX TWO ANTIQUE BRONZE",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "RO+UV",
    tank: "Wall Mount",
    img: "/products/2-10.webp",
    features: ["RO + UV WATER PURIFIER WITH STORAGE"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "LX TWO CHARCOAL BLACK",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "RO+UV",
    tank: "Wall Mount",
    img: "/products/2-11.webp",
    features: ["RO + UV WATER PURIFIER WITH STORAGE"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "LX TWO CHERRY RED",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "RO+UV",
    tank: "Wall Mount",
    img: "/products/2-12.webp",
    features: ["RO + UV WATER PURIFIER WITH STORAGE"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "LX TWO EMERALD GREEN",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "RO+UV",
    tank: "Wall Mount",
    img: "/products/2-13.webp",
    features: ["RO + UV WATER PURIFIER WITH STORAGE"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "LX TWO GUN METAL",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "RO+UV",
    tank: "Wall Mount",
    img: "/products/2-14.webp",
    features: ["RO + UV WATER PURIFIER WITH STORAGE"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "LX TWO OCEAN BLUE",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "RO+UV",
    tank: "Wall Mount",
    img: "/products/2-15.webp",
    features: ["RO + UV WATER PURIFIER WITH STORAGE"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "ZURIC BLACK",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "RO+UV",
    tank: "Wall Mount",
    img: "/products/2-16.webp",
    features: ["RO + UV WATER PURIFIER WITH STORAGE"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "ZURIC WHITE",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "RO+UV",
    tank: "Wall Mount",
    img: "/products/2-17.webp",
    features: ["RO + UV WATER PURIFIER WITH STORAGE"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Aqua Roma Black",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "RO+UV+UF",
    tank: "10L Tank",
    img: "/products/5-aqua-roma-blk.webp",
    features: ["RO + UV + UF + TDS CONTROLER + ACTIVE COPPER/B12 ALKALINE FILTER"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Aqua Roma White",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "RO+UV+UF",
    tank: "10L Tank",
    img: "/products/6-aqua-roma-white.webp",
    features: ["RO + UV + UF + TDS CONTROLER + ACTIVE COPPER/B12 ALKALINE FILTER"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Alfa Transparent",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "RO+UV",
    tank: "Wall Mount",
    img: "/products/64-alfa-transparent.webp",
    features: ["RO + UV + TDS + UF WATER PURIFIER WITH STORAGE"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Aqua Jade Blue",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "RO+UV",
    tank: "Wall Mount",
    img: "/products/68-aqua-jade-blue.webp",
    features: ["RO + UV WATER PURIFIER WITH STORAGE"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Aqua Jade Sky Blue",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "RO+UV",
    tank: "Wall Mount",
    img: "/products/69-aqua-jade-skyblue.webp",
    features: ["RO + UV WATER PURIFIER WITH STORAGE"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Aqua Jade Grey",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "RO+UV",
    tank: "Wall Mount",
    img: "/products/70-aqua-jade-grey.webp",
    features: ["RO + UV WATER PURIFIER WITH STORAGE"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Aqua Jade Black",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "RO+UV",
    tank: "Wall Mount",
    img: "/products/71-aqua-jade-black.webp",
    features: ["RO + UV WATER PURIFIER WITH STORAGE"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Aqua Jade Comrade Blue",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "RO+UV",
    tank: "Wall Mount",
    img: "/products/72-aqua-jade-comrade-blue.webp",
    features: ["RO + UV WATER PURIFIER WITH STORAGE"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Aqua Grand +",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "RO+UV",
    tank: "Wall Mount",
    img: "/products/73-aqua-grand-plus.webp",
    features: ["RO + UV WATER PURIFIER WITH STORAGE"],
    categoryId: "domestic-ro",
    featured: true},
  {
    name: "SS Domestic",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/96-ss-domestic.webp",
    features: ["RO Residential Water Purifier"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Aqua Digi White",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "15L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/79-aqua-digi-white.webp",
    features: ["RO+UV+UF+TDS CONTROLLER WITH LARGE STORAGE"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Aqua Digi Black",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "15L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/79-a-aqua-digi-black.webp",
    features: ["RO+UV+UF+TDS CONTROLLER WITH LARGE STORAGE"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Aqua XL Blue",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "15L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/80-aqua-xl-blue.webp",
    features: ["RO+UV+UF+TDS CONTROLLER WITH LARGE STORAGE"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Aqua XL Black",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "15L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/81-aqua-xl-blk.webp",
    features: ["RO+UV+UF+TDS CONTROLLER WITH LARGE STORAGE"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Aqua Glory Blue",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "15L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/82-aqua-glory-blue.webp",
    features: ["RO+UV+UF+TDS CONTROLLER WITH LARGE STORAGE"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Aqua Glory Sky Blue",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "15L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/83-aqua-glory-skyblue.webp",
    features: ["RO+UV+UF+TDS CONTROLLER WITH LARGE STORAGE"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Aqua Glory Black",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "15L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/84-aqua-glory-black.webp",
    features: ["RO+UV+UF+TDS CONTROLLER WITH LARGE STORAGE"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Aqua Glory Full Black",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "15L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/85-aqua-glory-full-black.webp",
    features: ["RO+UV+UF+TDS CONTROLLER WITH LARGE STORAGE"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Aqua Pearl",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "15L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/86-aqua-pearl.webp",
    features: ["RO+UV+UF+TDS CONTROLLER WITH LARGE STORAGE"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Aqua Sonnet Blue",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "15L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/87-aqua-sonnet-blue.webp",
    features: ["RO+UV+UF+TDS CONTROLLER WITH LARGE STORAGE"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Aqua Sonnet Sky Blue",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "15L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/88-aqua-sonnet-sky-blue.webp",
    features: ["RO+UV+UF+TDS CONTROLLER WITH LARGE STORAGE"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Aqua Sonnet Black",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "15L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/89-aqua-sonnet-black.webp",
    features: ["RO+UV+UF+TDS CONTROLLER WITH LARGE STORAGE"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Aqua Sonnet Grey",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "15L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/90-aqua-sonnet-grey.webp",
    features: ["RO+UV+UF+TDS CONTROLLER WITH LARGE STORAGE"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Aqua Grand New",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "15L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/91-aqua-grand-new.webp",
    features: ["RO+UV+UF+TDS CONTROLLER WITH LARGE STORAGE"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Lexpure",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "RO+UV",
    tank: "Wall Mount",
    img: "/products/92-lexpure.webp",
    features: ["RO + UV WATER PURIFIER WITH STORAGE"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Zetta Nova Star",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "15L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/95-zetta-nova-star.webp",
    features: ["RO+UF+ALKALINE+TAV WATER PURIFIER WITH LARGE STORAGE", "FLOW PER HOUR-12 LTRS CONSUMPTION PER DAY 30-60 LTRS"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Aqua X Thunder",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "15L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/97-aqua-x-thunder.webp",
    features: ["RO+UV+UF+TDS CONTROLLER WITH LARGE STORAGE"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Lexpure Seron +",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "RO+UV",
    tank: "Wall Mount",
    img: "/products/101-lexpure-seron.webp",
    features: ["RO + SN + AA + TDS WATER PURIFIER WITH STORAGE"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Lexpure Olive",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "RO+UV",
    tank: "Wall Mount",
    img: "/products/102-lexpure-olive.webp",
    features: ["RO + SN + AA + TDS WATER PURIFIER WITH STORAGE"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Aqua Pearl (Emerald Copper Technology)",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/157-aqua-pearl.webp",
    features: ["RO+UV+COPPER+ALKALINE"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Prolife Fiesta Copper",
    brand: "PROLIFE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/158-prolife.webp",
    features: ["RO+UV+UF+TDS+COPPER WITH TOUCH SCREEN"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "AQUA EMERALD BLACK RO + UV",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/3-1.webp",
    features: ["Under Sink RO System"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "AQUA NINE WHITE",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/3-2.webp",
    features: ["Under Sink RO System"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "HOT AND COLD WAVE",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/3-3.webp",
    features: ["Under Sink RO System"],
    categoryId: "dispensers",
    featured: false},
  {
    name: "UNDER SINK RO MERLIN",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/3-4.webp",
    features: ["Under Sink RO System"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "UNDER SINK RO OLIVAR",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/3-5.webp",
    features: ["Under Sink RO System"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "UNDER SINK RO AQUA C3",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/3-6.webp",
    features: ["Under Sink RO System"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "UNDER SINK RO KENT EXCELL PLUS",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/3-7.webp",
    features: ["Under Sink RO System"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "UNDER SINK RO SYSTEM",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/3-8.webp",
    features: ["Under Sink RO System"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Wave-4G-HOT AND COLD (RED)",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/3-9.webp",
    features: ["Under Sink RO System"],
    categoryId: "dispensers",
    featured: false},
  {
    name: "WAVE-4G-HOT-COLD (BLUE)",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/3-10.webp",
    features: ["Under Sink RO System"],
    categoryId: "dispensers",
    featured: false},
  {
    name: "Aqua Guard Classic",
    brand: "AQUA GUARD",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/125-aqua-guard-classic.webp",
    features: ["RO+UV  WATER PURIFIER WITH COPPER MAXX TECHNOLOGY"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Aqua Guard Classic +",
    brand: "AQUA GUARD",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/126-aqua-guard-classic.webp",
    features: ["UV  WATER PURIFIER WITH COPPER MAXX TECHNOLOGY"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Aqua Guard Reviva Next RO",
    brand: "AQUA GUARD",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/127-aqua-guard-reviva-next.webp",
    features: ["RO+UV E-BOILING+ACTIVE COPPER+MTDS+MINERAL GUARD TECHNOLOGY WATER PURIFIER"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Aqua Guard Magna",
    brand: "AQUA GUARD",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/128-aqua-guard-magna.webp",
    features: ["AQUA GUARD MAGNA RO+UV+MTDS TECHNOLOGY"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Aqua Guard Enhance",
    brand: "AQUA GUARD",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "Standard",
    stages: "RO+UV",
    tank: "Standard Tank",
    img: "/products/147-a-aqua-sure-enhancer.webp",
    features: ["RO + UV LED", "Active Copper Technology", "Mineral Guard Technology"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Blue Star Regulas",
    brand: "BLUE STAR",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/136-blue-star-regauls.webp",
    features: ["BLUE STAR REGAULS RO+UV+UF WITH HOT + ALKALINE"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Blue Star Iconia",
    brand: "BLUE STAR",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/137-blue-star-iconia.webp",
    features: ["ICONIA (HRRO+UV+UF+ALKALINE)"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Blue Star Aristo",
    brand: "BLUE STAR",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/138-blue-star-aristo.webp",
    features: ["AQUA GUARD MAGNA RO+UV+MTDS TECHNOLOGY"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Blue Star Pristino",
    brand: "BLUE STAR",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/139-blue-star-pristina.webp",
    features: ["UV WATER PURIFIER"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Blue Star Genia Black",
    brand: "BLUE STAR",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/140-blue-star-genia-black.webp",
    features: ["RO + UF WATER PURIFIER"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Blue Star Genia White",
    brand: "BLUE STAR",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/141-blue-star-genia-white.webp",
    features: ["RO + UF WATER PURIFIER"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Blue Life Metro Plus",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/142-blue-life-metro-plus.webp",
    features: ["UF and UV Water Purifier"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Blue Life Tulips Plus",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/143-blue-life-tulips-plus.webp",
    features: ["RO+UV Water Purifier"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Blue Life Hygiene",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "15L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/144-blue-life-hygiene.webp",
    features: ["RO Water Purifier"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Blue Life Ripple Scientech (RO)",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/145-blue-life-ripple-scientech.webp",
    features: ["RO Water Purifier"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Blue Life Ripple Scientech (RO+UV)",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/146-blue-life-ripple-scientech.webp",
    features: ["RO+UV Water Purifier"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Blue Mount Elite Star",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/133-blue-mount-elite-star.webp",
    features: ["ALKALINE RO EVA ALKALINE RO WATER PURIFIER"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Blue Mount Crown Star",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/134-blue-mount-crown-star.webp",
    features: ["ALKALINE RO + UF WATER PURIFIER"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Kent Pearl Star",
    brand: "KENT",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/121-kent-pearl-star.webp",
    features: ["RO+UV+UF+TDS Control process", "KENT WATER PURIFIER"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Kent Crystal Alkaline",
    brand: "KENT",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "Standard",
    stages: "Multi Stage",
    tank: "Standard Tank",
    img: "/products/122-kent-crystal-alkaline.webp",
    features: [
    "Advanced Alkaline technology balances pH levels up to 8.5+.",
    "Enhances water with essential minerals for boosted immunity.",
    "Multi-stage RO+UV+UF+TDS Control purification process.",
    "Zero Water Wastage technology saves every drop of rejected water."
  ],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Kent Pearl",
    brand: "KENT",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "15L/Hr",
    stages: "RO+UV+UF",
    tank: "Standard Tank",
    img: "/products/123-kent-pearl.webp",
    features: ["RO + UV + UF + TDS Control + Alkaline + UV in Tank Water Purifier"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Kent Grand +",
    brand: "KENT",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "15L/Hr",
    stages: "RO+UV+UF",
    tank: "Standard Tank",
    img: "/products/124-kent-grand.webp",
    features: ["RO + UV + UF + TDS Control  PROCESS"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Livpure Glitz Silver",
    brand: "LIVPURE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/129-livpure-glitz-silver.webp",
    features: ["RO UF MINERALIZER 7 LTR RO WATER PURIFIER"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Livpure Glitz Plus",
    brand: "LIVPURE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/130-livpure-glitz-plus.webp",
    features: ["RO UF MINERALIZER 7 LTR RO WATER PURIFIER"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Livpure Bolt + Copper",
    brand: "LIVPURE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "Standard",
    stages: "RO",
    tank: "Standard Tank",
    img: "/products/131-livpure-bolt-copper.webp",
    features: ["RO+UF+MIN Water Purifier"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Merlin Matrix White",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/106-merlin-matrix-white.webp",
    features: ["RO+ALK+UV+UF+TDS WATER PURIFIER"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Merlin Matrix Black",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/107-merlin-matrix-black.webp",
    features: ["RO+ALK+UV+UF+TDS WATER PURIFIER"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Merlin Planet Black",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/108-merlin-planet-black.webp",
    features: ["RO+ALK+UV+UF+TDS WATER PURIFIER"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Merlin Planet White",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/109-merlin-planet-white.webp",
    features: ["RO+ALK+UV+UF+TASTE ADJUSTER WATER PURIFIER"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Merlin Rapid Black",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/110-merlin-rapid-black.webp",
    features: ["RO+ALK+UV+UF+TASTE ADJUSTER WATER PURIFIER"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Merlin Rapid White",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/111-merlin-rapid-white.webp",
    features: ["RO+ALK+UV+UF+TDS WATER PURIFIER"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Merlin Rapid Lite",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/112-merlin-rapid-lite.webp",
    features: ["RO+ALK+UV+UF+TDS WATER PURIFIER"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Merlin Alfa Black",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/113-merlin-alfa-black.webp",
    features: ["RO+ALK+UV+UF+TDS WATER PURIFIER"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Merlin Planet Copper",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/114-merlin-planet-copper.webp",
    features: ["RO+ALK+UV+UF+TASTE ADJUSTER WATER PURIFIER"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Aqua Sure Forbes Delight",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "7L Tank",
    img: "/products/147-aqua-sure-forbs-delite.webp",
    features: ["RO+UV WATER PURIFIER WITH STORAGE MODEL"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Havells Digi Plus Alkaline",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "15L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/148-havells-digi-plus-alkaline.webp",
    features: ["RO & UV Purified Alkaline Water"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Philips UV Purifier",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/149-philips-uv-purifier.webp",
    features: ["UV PURIFIER WITH OUT STORAGE"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "AO Smith Pro Planet P4",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/150-ao-smith-proplanet-p4.webp",
    features: ["RO + SCMT + UV LED 5 Ltrs Water Purifier"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "AO Smith Pro Planet P7",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/151-ao-smith-proplanet-p7.webp",
    features: ["RO+SCMT 10 Ltrs Water Purifier"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Faber C Guard",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/152-faber-c-guard-ro-uv-mat-vit-c.webp",
    features: ["RO + MAT Water Purifier"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Pure It Hul",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "RO+UV",
    tank: "Wall Mount",
    img: "/products/153-pureit-hul.webp",
    features: ["Copper+ Mineral + RO + UV"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "LG RO",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/154-lg-ro.webp",
    features: ["(RO) Reverse Osmosis Water Purifier"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Tago",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "RO+UV",
    tank: "Wall Mount",
    img: "/products/3-tago.webp",
    features: ["RO"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Swan Ro",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/4-swan-ro.webp",
    features: ["MISTY SWAN RO"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Wave Krystal",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/7-wave-krystal.webp",
    features: ["KRYSTAL AUTO TDS RO | UV | UF | COPPER"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Genpure Ultima",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "RO+UV",
    tank: "Wall Mount",
    img: "/products/8-genpure-ultima.webp",
    features: ["RO + UV +TDS ADJUSTABLE"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Wave Kombo",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "RO+UV",
    tank: "Wall Mount",
    img: "/products/9-wave-kombo.webp",
    features: ["WAVE KOMBO RO+UV"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Chrome 1st Choise Model",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/10-chrome.webp",
    features: ["RO+ UV+ TDS+ UF+ COPPER FILTER CARTRIDGE"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Org Todi",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/11-org-todi.webp",
    features: ["WATER PURIFIER TODI ALKLINATOR  PURIFICATION CAPACITY 15 LITER/HOUR"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Wave 5G",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/1-wave4g.webp",
    features: ["HOT COLD & NORMAL ALKALINE WATER PURIFIER"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "No Bact",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "Multi Stage",
    tank: "Wall Mount",
    img: "/products/2-no-bactt.webp",
    features: ["(NORMAL + HOT)"],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Prolife Fiesta Full Black",
    brand: "PROLIFE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "Standard",
    stages: "Multi Stage",
    tank: "Standard Tank",
    img: "/products/115-prolife-fiesta-full-black.webp",
    features: [
    "Sophisticated all-black matte finish for premium dark-themed kitchens.",
    "Engineered specifically to treat hard water up to 2000 ppm TDS.",
    "Multi-stage purification leaves water tasting crisp and sweet.",
    "Large storage tank ensures water availability during power cuts."
  ],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Prolife Fiesta White",
    brand: "PROLIFE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "Standard",
    stages: "Multi Stage",
    tank: "Standard Tank",
    img: "/products/116-prolife-fiesta-white.webp",
    features: [
    "Classic, pristine white exterior that blends into any home environment.",
    "Easy-to-clean surface requires minimal exterior maintenance.",
    "Utilizes copper-impregnated filters for natural antimicrobial properties.",
    "Ensures long-lasting membrane life with pre-filtration staging."
  ],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Prolife Fiesta Black Transparent",
    brand: "PROLIFE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "Standard",
    stages: "Multi Stage",
    tank: "Standard Tank",
    img: "/products/117-prolife-fiesta-black-tranparent.webp",
    features: [
    "Modern transparent fascia allows you to see the purification in action.",
    "Combines the sleekness of black with high-tech visual appeal.",
    "Powerful UV sterilization stage eliminates 99.9% of bacteria and viruses.",
    "Designed for quick, hassle-free filter replacements."
  ],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Prolife Accent Alkaline",
    brand: "PROLIFE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "Standard",
    stages: "Multi Stage",
    tank: "Standard Tank",
    img: "/products/118-prolife-accent-alkaline.webp",
    features: [
    "Affordable entry into premium alkaline water consumption.",
    "Sleek, modern aesthetic designed for modular kitchen mounting.",
    "Multi-stage filtration ensures 100% safe drinking water from any source.",
    "Includes smart LED indicators for tank full and purification status."
  ],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Prolife Asta",
    brand: "PROLIFE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "Standard",
    stages: "Multi Stage",
    tank: "Standard Tank",
    img: "/products/119-prolife-asta.webp",
    features: [
    "Comprehensive RO+UV+UF purification for absolute safety.",
    "Highly effective against heavy metals found in borewell water.",
    "Compact space-saving design with a robust ABS food-grade plastic body.",
    "High purification capacity handles peak family hydration needs effortlessly."
  ],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Prolife Neon",
    brand: "PROLIFE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "Standard",
    stages: "Multi Stage",
    tank: "Standard Tank",
    img: "/products/120-prolife-neon.webp",
    features: [
    "Striking neon-accented design elevates your kitchen decor.",
    "Features a transparent water level indicator for easy monitoring.",
    "Advanced membrane technology removes dissolved impurities like arsenic and fluoride.",
    "Auto-on and auto-off functionality for hands-free convenience."
  ],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "25 LPH Skid",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "25L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/155-25-lph-skid.webp",
    features: ["Fully Stainless Steel Body With 150 GPD High Performance Copper Winded Booster Pump. Purification : 25 Liter Per Hour , One 150 Gpd Booster Pump , Two Pices Membrane And One Activated Carbon Filter.Purification Technology : RO : Type : Electrical, Purification Stage :Stage 1: 5 microns inline PP filter || Stage 2: Granule Active Carbon Filter ||Stage 3: Block Active Carbon Filter || Stage 4: RO Membrane ||Stage 5: Post Carbon Filter.Max. Duty Cycle Per Day 100 Litre Suitable For Home , Office , Hotel , Restaurant, Cafe and Factory.Water Purifier System Which Run Upto 2000 TDS. Installation charges are 599 Installation provided by seller & charges Paid by customer (Customer Care No.18001202253) Chargeble After The Installation(Visit charge is 150-300).No Warranty for Filters, Filters are Consumables, Get Blocked or Choked Because of Water Only. If Water Quality is Good Filters Life will be More, If Water Quality is Bad (More Turbidity or More TDS) Filters Life will be Less. Our Excutive Will Solve Customer Problem Within 24 to 48 Hour.", "FLOW PER HOUR 25 LTRS", "PER DAY CONSUMPTION:70-130 LTRS", "Technician will be arranged once the product reaches to customer. For installation Customer has to pay Rs.400 to Rs.500 Extra to the technician depends on city and location. Kindly call on Toll-Free No.18001202253  to arrange the technician"],
    categoryId: "commercial-ro",
    featured: false},
  {
    name: "25 LPH Double Pump",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "25L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/156-25-lph-double-pump.webp",
    features: ["Fully Stainless Steel Body With 150 GPD High Performance Copper Winded Booster Pump. Purification : 25 Liter Per Hour , One 150 Gpd Booster Pump , Two Pices Membrane And One Activated Carbon Filter.Purification Technology : RO : Type : Electrical, Purification Stage :Stage 1: 5 microns inline PP filter || Stage 2: Granule Active Carbon Filter ||Stage 3: Block Active Carbon Filter || Stage 4: RO Membrane ||Stage 5: Post Carbon Filter.Max. Duty Cycle Per Day 100 Litre Suitable For Home , Office , Hotel , Restaurant, Cafe and Factory.Water Purifier System Which Run Upto 2000 TDS. Installation charges are 599 Installation provided by seller & charges Paid by customer (Customer Care No.18001202253) Chargeble After The Installation(Visit charge is 150-300).No Warranty for Filters, Filters are Consumables, Get Blocked or Choked Because of Water Only. If Water Quality is Good Filters Life will be More, If Water Quality is Bad (More Turbidity or More TDS) Filters Life will be Less. Our Excutive Will Solve Customer Problem Within 24 to 48 Hour.", "FLOW PER HOUR 25 LTRS", "PER DAY CONSUMPTION:70-130 LTRS", "Technician will be arranged once the product reaches to customer. For installation Customer has to pay Rs.400 to Rs.500 Extra to the technician depends on city and location. Kindly call on Toll-Free No.18001202253  to arrange the technician"],
    categoryId: "commercial-ro",
    featured: false},
  {
    name: "25 LPH Whale",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "25L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/157-25-lph-whale.webp",
    features: ["Fully Stainless Steel Body With 150 GPD High Performance Copper Winded Booster Pump. Purification : 25 Liter Per Hour , One 150 Gpd Booster Pump , Two Pices Membrane And One Activated Carbon Filter.Purification Technology : RO : Type : Electrical, Purification Stage :Stage 1: 5 microns inline PP filter || Stage 2: Granule Active Carbon Filter ||Stage 3: Block Active Carbon Filter || Stage 4: RO Membrane ||Stage 5: Post Carbon Filter.Max. Duty Cycle Per Day 100 Litre Suitable For Home , Office , Hotel , Restaurant, Cafe and Factory.Water Purifier System Which Run Upto 2000 TDS. Installation charges are 599 Installation provided by seller & charges Paid by customer (Customer Care No.18001202253) Chargeble After The Installation(Visit charge is 150-300).No Warranty for Filters, Filters are Consumables, Get Blocked or Choked Because of Water Only. If Water Quality is Good Filters Life will be More, If Water Quality is Bad (More Turbidity or More TDS) Filters Life will be Less. Our Excutive Will Solve Customer Problem Within 24 to 48 Hour.", "FLOW PER HOUR 25 LTRS", "PER DAY CONSUMPTION:70-130 LTRS", "Technician will be arranged once the product reaches to customer. For installation Customer has to pay Rs.400 to Rs.500 Extra to the technician depends on city and location. Kindly call on Toll-Free No.18001202253  to arrange the technician"],
    categoryId: "commercial-ro",
    featured: false},
  {
    name: "50 LPH Plant",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "50L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/158-50-lph-plant.webp",
    features: ["Drink pure water for a healthy life.||Purification Technology : RO : Type : Electrical, Purification Stage :Stage 1: 5 microns inline PP filter || Stage 2: Granule Active Carbon Filter ||Stage 3: Block Active Carbon Filter || Stage 4: RO Membrane ||Stage 5: Post Carbon Filter.Fully automatic RO water purifier  Stainless Steel Body With Two 150 GPD high-performance copper winding motor. RO Water Purifier System Which runs up to 2000 TDS level of Input Water from Both Ground water and Munciple Supply. Purification Capacity: 50 Liter Per Hour,2 pcs 150 Gpd Booster Pump, 4 pcs membrane. Max. duty cycle per day: 200 To 300 Ltr,Suitable for Office, Restaurant, Cafe, Resort and Factory. This water purifier has a capacity of 50 Ltr, so as to ensure continuous supply of purified water even when there is no electricity or running tap water. After The Installation(Visit charge is 250-300).No Warranty for Filters, Filters are Consumables, Get Blocked or Choked Because of Water Only. If Water Quality is Good Filters Life will be More, If Water Quality is (More Turbidity or More TDS) Filters Life will be Less. Our Excutive Will Solve Customer Problem Within 24 to 48 Hour.", "Technician will be arranged once the product reaches to customer. For installation Customer has to pay Rs.400 to Rs.500 Extra to the technician depends on city and location. Kindly call on Toll-Free No.18001202253  to arrange the technician"],
    categoryId: "commercial-ro",
    featured: false},
  {
    name: "100 LPH Plant",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "100L/Hr",
    stages: "5 Stage",
    tank: "Wall Mount",
    img: "/products/159-100-lph-plant.webp",
    features: ["Fully Stainless Steel Body With Two 300 GPD High Performance Copper Winded Booster Pump", "Fully automatic RO water purifier with Auto Shut Off Function || Purification Technology : RO : Type : Electrical, Purification Stage :Stage 1: 5 microns inline PP filter || Stage 2: Granule Active Carbon Filter ||Stage 3: Block Active Carbon Filter || Stage 4: RO Membrane ||Stage 5: Post UV Filter", "Max. Duty Cycle Per Day500 - 700 Litre Suitable For Home , Office , Hotel , Restaurant, Cafe and Factory", "Purification : 100 Liter Per Hour , Two 300 Gpd Booster Pump , Four Pices Membrane 150 GPD And One Activated Carbon Filter"],
    categoryId: "commercial-ro",
    featured: false},
  {
    name: "250 LPH Plant",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "Multi Stage",
    tank: "Wall Mount",
    img: "/products/160-250-lph-plant.webp",
    features: [
    "Heavy-duty 250 Liters Per Hour commercial purification capacity.",
    "Ideal for schools, restaurants, and mid-sized office complexes.",
    "Equipped with commercial-grade high-pressure pumps for continuous operation.",
    "Effectively treats high-TDS groundwater and municipal supplies."
  ],
    categoryId: "industrial",
    featured: false},
  {
    name: "500 LPH Plant",
    brand: "AQUA CARE",
    tag: "RO Systems",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "Multi Stage",
    tank: "Wall Mount",
    img: "/products/161-500-lph-plant.webp",
    features: [
    "Massive 500 Liters Per Hour output for large-scale institutional use.",
    "Perfect for hospitals, large corporate buildings, and manufacturing units.",
    "Features automated flushing and industrial-grade RO membranes.",
    "Built-in TDS controller ensures consistent output quality across variable water sources."
  ],
    categoryId: "industrial",
    featured: false},
  {
    name: "Desire Plus",
    brand: "AQUA CARE",
    tag: "Our Products",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "Multi Stage",
    tank: "Wall Mount",
    img: "/products/desire-plus.webp",
    features: [
    "Premium water dispenser offering instant hot, cold, and normal water.",
    "Perfect hydration station for office breakrooms and waiting areas.",
    "Child-lock feature on the hot water faucet ensures absolute safety.",
    "Energy-efficient compressor cooling operates silently in the background."
  ],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Reflection Plus",
    brand: "AQUA CARE",
    tag: "Our Products",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "Multi Stage",
    tank: "Wall Mount",
    img: "/products/reflection-plus.webp",
    features: [
    "Dual-purpose system combining high-end purification with instant temperature control.",
    "Elegant reflective glass-like finish makes it a centerpiece.",
    "Eco-mode ensures lower electricity consumption during night hours.",
    "Provides boiling water for tea/coffee and chilled water for summer days."
  ],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Rhino Plus",
    brand: "AQUA CARE",
    tag: "Our Products",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "Multi Stage",
    tank: "Wall Mount",
    img: "/products/rhino-plus.webp",
    features: [
    "Upgraded Rhino model featuring additional UV and UF sterilization.",
    "Provides industrial-level durability with commercial-level water safety.",
    "Ideal for large joint families or areas with unpredictable water quality.",
    "Maintains natural mineral balance while eliminating harmful pathogens."
  ],
    categoryId: "domestic-ro",
    featured: false},
  {
    name: "Rhino",
    brand: "AQUA CARE",
    tag: "Our Products",
    price: "Contact Us",
    mrp: null,
    liters: "12L/Hr",
    stages: "Multi Stage",
    tank: "Wall Mount",
    img: "/products/rhino.webp",
    features: [
    "Rugged, highly durable build designed for tough rural environments.",
    "Extra-large storage capacity minimizes dependence on electricity.",
    "Heavy-duty sediment and carbon blocks tackle highly turbid water.",
    "Built to last with minimal servicing required over its lifespan."
  ],
    categoryId: "domestic-ro",
    featured: false},
];

export const AMC_PLANS: AmcPlanItem[] = [
  {
    name: "Silver",
    price: "Contact Us",
    period: "/year",
    color: "from-slate-400 to-slate-600",
    features: [
      "3 Services/Year (Every 4 Months)",
      "1 Sediment Filter Replaced per Service",
      "Preventive Check & Cleaning",
      "Phone Support",
    ],
  },
  {
    name: "Gold",
    price: "Contact Us",
    period: "/year",
    color: "from-amber-400 to-yellow-600",
    highlight: true,
    features: [
      "3 Services/Year (Every 4 Months)",
      "3 Filters Replaced per Service (1 Carbon + 2 Sediment)",
      "Priority On-Site Support",
      "Full System Health Check",
      "Free Emergency Visit",
    ],
  },
  {
    name: "Platinum",
    price: "Contact Us",
    period: "/year",
    color: "from-cyan-500 to-blue-600",
    features: [
      "3 Services/Year (Every 4 Months)",
      "4 Filters Replaced per Service (2 Carbon + 2 Sediment)",
      "24/7 Priority Support",
      "Complete System Overhaul",
      "Free Emergency Visit",
      "Annual Deep Sanitization",
    ],
  },
];

export const TESTIMONIALS: TestimonialItem[] = [
  {
    name: "Rajesh Kumar",
    loc: "Karur",
    stars: 5,
    text: "Excellent service! My RO purifier was installed within hours. The water quality is fantastic. Highly recommend Yuvanthika Aquacare to everyone.",
  },
  {
    name: "Priya Lakshmi",
    loc: "Kulithalai",
    stars: 5,
    text: "Solar water heater எடுத்தோம். மாதம் EB கட்டணம் மிச்சமாகிறது. Perfect installation and after-sales support. 5 stars!",
  },
  {
    name: "Mohammed Farooq",
    loc: "Tiruchirappalli",
    stars: 5,
    text: "Best AMC plan in the region. They come on time, professional staff, and genuine spare parts. Trust them completely.",
  },
  {
    name: "Kavitha Devi",
    loc: "Aravakurichi",
    stars: 5,
    text: "Washing machine repair was done same day. Technician explained the problem clearly. Very transparent pricing. Great experience!",
  },
];

export const WHY_CHOOSE_POINTS: WhyChoosePoint[] = [
  { icon: Clock, title: "Same-Day Service", desc: "Book before noon, get service today" },
  { icon: Award, title: "Certified Technicians", desc: "Factory-trained, background-verified" },
  { icon: Shield, title: "Genuine Parts", desc: "100% authentic spare parts only" },
  { icon: ThumbsUp, title: "Price Transparency", desc: "No hidden charges, ever" },
];

export const BOOKING_STEPS: BookingStep[] = [
  { step: "01", title: "Call or WhatsApp Us", desc: "Reach us anytime between 8 AM – 8 PM" },
  { step: "02", title: "Schedule a Visit", desc: "Pick a time slot that works for you" },
  { step: "03", title: "Expert Arrives", desc: "Certified technician at your doorstep" },
];

export const CONTACT_CARDS: ContactChannelCard[] = [
  {
    icon: "phone",
    title: "Call Us",
    lines: [PHONE_DISPLAY, "Mon–Sun: 8 AM – 8 PM"],
    link: CALL,
    label: "Call Now",
    color: "from-cyan-500 to-blue-600",
  },
  {
    icon: "message",
    title: "WhatsApp",
    lines: ["Chat with us 24/7", "Quick response guaranteed"],
    link: WHATSAPP,
    label: "Open WhatsApp",
    color: "from-green-500 to-emerald-600",
  },
  {
    icon: "map",
    title: "Visit Us",
    lines: [...ADDRESS_LINES],
    link: MAPS_DIRECTIONS_URL,
    label: "Get Directions",
    color: "from-orange-500 to-red-500",
  },
];

import { prisma } from "@/lib/db";

export const FOOTER_SERVICE_LINKS: FooterServiceLink[] = SERVICES.map((s) => ({
  label: s.title,
  href: `/services/${s.slug}`,
}));

export async function getDynamicProducts(): Promise<ProductItem[]> {
  if (prisma) {
    try {
      const dbProducts = await prisma.product.findMany({
        orderBy: { createdAt: "desc" },
      });
      if (dbProducts.length > 0) {
        return dbProducts.map((p) => ({
          name: p.name,
          brand: p.brand,
          tag: p.featured ? "Featured" : "Pure Water",
          price: p.price,
          mrp: p.mrp || null,
          liters: p.liters || "12L/Hr",
          stages: p.stages || "Multi Stage",
          tank: p.tank || "Storage Tank",
          img: p.image,
          features: p.features.length > 0 ? p.features : ["High Rejection RO Membrane", "Alkaline Mineral Cartridge"],
          categoryId: p.categoryId,
          featured: p.featured,
        }));
      }
    } catch (e) {
      console.warn("DB product query fallback:", e);
    }
  }
  return PRODUCTS;
}

